import type { Metadata } from "next";
import CardNewsGallery, { type CardNewsItem } from "@/components/card-news/card-news-gallery";
import { PageHeading } from "@/components/section/page-heading";

export const metadata: Metadata = {
  title: "카드뉴스 | GoTechy",
  description: "Reddit r/artificial, r/technology에서 엄선한 AI & 기술 트렌드를 카드뉴스로 빠르게 만나보세요.",
  alternates: { canonical: "/card-news" },
};

/* Reddit AI/Tech 트렌드 기반 샘플 데이터 */
const CARD_NEWS_DATA: CardNewsItem[] = [
/* TECH-NEWS-PIPELINE-DATA:START */
  {
    id: 56,
    slug: "토스팀이-ai-파도를-마주하는-방법-ai-surf-day",
    title: "토스팀이 AI 파도를 마주하는 방법: AI Surf Day",
    summary: "파도를 멈출 수는 없지만, 서핑하는 방법은 배울 수 있다.",
    content: "",
    category: "news",
    image_url: "/card-news/토스팀이-ai-파도를-마주하는-방법-ai-surf-day.png",
    external_link: "https://toss.tech/article/ai-surf-day",
    tags: ["AI", "AI", "Surf"],
    created_at: "2026-06-05",
    span: "",
  },
  {
    id: 55,
    slug: "hyundai-boston-dynamics-atlas-learn-by-watching",
    title: "Hyundai·Boston Dynamics — Atlas, 인간 시연 영상으로 학습",
    summary: "현대차·보스턴 다이내믹스가 Atlas 휴머노이드를 인간 작업 영상 시청만으로 학습시키는 새 학습 파이프라인을 공개. 텔레오퍼레이션·시뮬레이션 의존도를 낮추고 데이터 확보 비용을 크게 절감한 접근.",
    content: "",
    category: "ai",
    image_url: "/card-news/hyundai-boston-dynamics-atlas-learn-by-watching.png",
    external_link: "https://www.reddit.com/r/artificial/comments/1tnk2qd/hyundaiboston_dynamics_is_going_to_train_atlas/",
    tags: ["BostonDynamics", "Atlas", "휴머노이드"],
    created_at: "2026-05-26",
    span: "",
  },
  {
    id: 54,
    slug: "figure-ai-24-7-package-sorting-livestream",
    title: "Figure AI — 휴머노이드 8일간 24/7 패키지 분류 라이브스트림 공개",
    summary: "Figure AI가 휴머노이드 로봇이 8일 동안 24시간 쉬지 않고 패키지를 분류하는 모습을 라이브스트림으로 공개. 데모 영상이 아닌 실제 산업 환경 지속 동작을 보인 첫 휴머노이드 사례로 주목.",
    content: "",
    category: "ai",
    image_url: "/card-news/figure-ai-24-7-package-sorting-livestream.png",
    external_link: "https://www.reddit.com/r/artificial/comments/1tmtq3p/figure_ai_had_a_livestream_of_their_robots/",
    tags: ["FigureAI", "휴머노이드", "물류로봇"],
    created_at: "2026-05-25",
    span: "",
  },
  {
    id: 53,
    slug: "musinsa-geometric-prior-25x-vlm-free",
    title: "무신사 — VLM 안 쓰고 Geometric Prior로 25배 빠른 의류 디테일컷",
    summary: "무신사가 의류 디테일컷 자동화에 VLM 대신 Geometric Prior 기반 전통 컴퓨터 비전을 채택해 25배 속도를 얻은 사례를 공개. 'AI 만능' 대신 도메인 사전지식 활용이 더 효율적이었다는 실전 회고.",
    content: "",
    category: "dev",
    image_url: "/card-news/musinsa-geometric-prior-25x-vlm-free.png",
    external_link: "https://techblog.musinsa.com/vlm%EC%9D%84-%EC%93%B0%EC%A7%80-%EC%95%8A%EC%9D%80-%EC%9D%B4%EC%9C%A0-geometric-prior%EB%A1%9C-25%EB%B0%B0-%EB%B9%A0%EB%A5%B8-%EC%9D%98%EB%A5%98-%EB%94%94%ED%85%8C%EC%9D%BC%EC%BB%B7-%EC%9E%90%EB%8F%99%ED%99%94-ea9dc5ca2add",
    tags: ["무신사", "ComputerVision", "GeometricPrior"],
    created_at: "2026-05-24",
    span: "",
  },
  {
    id: 52,
    slug: "woowahan-rag-chatbot-system-context",
    title: "우아한공방 — 시스템 맥락 가진 RAG 챗봇 개발기",
    summary: "우아한형제들이 사내 시스템 맥락을 이해하는 RAG 챗봇 서비스를 공개. 단순 문서 검색이 아닌, 사내 서비스·코드·운영 컨텍스트를 임베딩 단계에서 결합해 실제 답변 정확도를 끌어올린 구조.",
    content: "",
    category: "dev",
    image_url: "/card-news/woowahan-rag-chatbot-system-context.png",
    external_link: "https://techblog.woowahan.com/26319/",
    tags: ["우아한형제들", "RAG", "챗봇"],
    created_at: "2026-05-23",
    span: "",
  },
  {
    id: 51,
    slug: "line-adk-context-token-40-percent",
    title: "LINE — ADK 컨텍스트 엔지니어링으로 토큰 소비 40% 절감",
    summary: "LINE Engineering이 Agent Development Kit(ADK)에서 컨텍스트 엔지니어링 3가지 기법으로 토큰 소비를 40% 줄인 사례를 공개. 시스템 프롬프트 구조화·툴 결과 정리·세션 상태 관리가 핵심.",
    content: "",
    category: "dev",
    image_url: "/card-news/line-adk-context-token-40-percent.png",
    external_link: "https://techblog.lycorp.co.jp/ko/cut-token-usage-40-percent-with-adk-context-engineering",
    tags: ["LINE", "ADK", "컨텍스트엔지니어링"],
    created_at: "2026-05-22",
    span: "",
  },
  {
    id: 50,
    slug: "kakao-messaging-stress-test-ai",
    title: "카카오 — 메시징 서버 스트레스 테스트 노하우와 AI가 덜어 준 부분",
    summary: "카카오가 메시징 서버의 스트레스 테스트 노하우를 공개했다. 시나리오 작성·로그 분석 같은 반복 작업을 AI에 위임하고 엔지니어는 부하 모델링·이상 패턴 해석에 집중하는 분업 구조가 핵심.",
    content: "",
    category: "dev",
    image_url: "/card-news/kakao-messaging-stress-test-ai.png",
    external_link: "https://tech.kakao.com/posts/822",
    tags: ["카카오", "스트레스테스트", "AI협업"],
    created_at: "2026-05-21",
    span: "",
  },
  {
    id: 49,
    slug: "line-ai-qa-augment",
    title: "LINE — 'AI 는 QA 를 대체하지 않았다, 확장했다'",
    summary: "LINE Engineering 이 사내 QA 직무가 생성형 AI 도입 이후 어떻게 진화했는지 공개했다. 결론은 '확장'. AI 가 반복 테스트 작성·재현 시나리오 빌드를 맡고, QA 는 도메인 위험 탐색에 집중하는 분업 모델.",
    content: "",
    category: "dev",
    image_url: "/card-news/line-ai-qa-augment.png",
    external_link: "https://techblog.lycorp.co.jp/ko/ai-augments-qa-rather-than-replacing-it",
    tags: ["LINE", "QA", "생성형AI"],
    created_at: "2026-05-20",
    span: "",
  },
  {
    id: 48,
    slug: "ai-hardware-startup-funding-q2",
    title: "AI 하드웨어 스타트업 Q2 자금 — Groq·Cerebras·Tenstorrent 3강 구도",
    summary: "AI 추론 가속 하드웨어 스타트업의 Q2 자금 흐름이 Groq·Cerebras·Tenstorrent 의 3강 구도로 정리됐다. NVIDIA 의 추론 시장 지배를 깨려는 흐름이지만 데이터센터 점유율은 여전히 미미.",
    content: "",
    category: "news",
    image_url: "/card-news/ai-hardware-startup-funding-q2.png",
    external_link: "https://www.semianalysis.com/p/inference-race",
    tags: ["AI하드웨어", "Groq", "Tenstorrent"],
    created_at: "2026-05-19",
    span: "",
  },
  {
    id: 47,
    slug: "anthropic-enterprise-agent-blueprint",
    title: "Anthropic Enterprise Agent Blueprint — 8주 도입 표준 패키지 공개",
    summary: "Anthropic 이 엔터프라이즈 에이전트 도입 표준 패키지를 공개. 8주 안에 PoC → 프로덕션 1개 워크플로 출시가 목표. Computer Use + Claude Code + MCP 조합 베스트프랙티스 가이드 포함.",
    content: "",
    category: "trend",
    image_url: "/card-news/anthropic-enterprise-agent-blueprint.png",
    external_link: "https://www.anthropic.com/solutions/enterprise",
    tags: ["Anthropic", "엔터프라이즈", "에이전트"],
    created_at: "2026-05-18",
    span: "",
  },
  {
    id: 46,
    slug: "musinsa-ai-pipeline-harness",
    title: "무신사 — '하네스로 제어하는 AI 파이프라인', Slow Query 자동 사냥 사례",
    summary: "무신사 물류플랫폼팀이 Slow Query 수집 → 정합성 검증 → PR 생성 → 리뷰 반영까지를 'AI 하네스'로 자동화한 경험을 공유했다. CloudWatch + LLM + 자체 휴리스틱 조합이 핵심. 매주 반복되던 작업이 사라졌다.",
    content: "",
    category: "dev",
    image_url: "/card-news/musinsa-ai-pipeline-harness.png",
    external_link: "https://techblog.musinsa.com/",
    tags: ["무신사", "AI파이프라인", "DevOps"],
    created_at: "2026-05-17",
    span: "",
  },
  {
    id: 45,
    slug: "stable-lm-3-edge-deploy",
    title: "StableLM 3 — 1.6B 모델로 GPT-3.5 급 한국어 성능, 모바일 추론 가능",
    summary: "Stability AI 의 StableLM 3 1.6B 모델이 한국어 KMMLU 에서 GPT-3.5 급 성능. INT4 양자화 시 720MB. 갤럭시 S24 / iPhone 16 에서 온디바이스 추론 데모 공개됨.",
    content: "",
    category: "ai",
    image_url: "/card-news/stable-lm-3-edge-deploy.png",
    external_link: "https://stability.ai/",
    tags: ["StableLM", "온디바이스", "한국어"],
    created_at: "2026-05-16",
    span: "",
  },
  {
    id: 44,
    slug: "openai-dev-day-spring-recap",
    title: "OpenAI Dev Day Spring — 핵심 발표 5개 요약, 'Realtime 가 진짜 게임체인저'",
    summary: "OpenAI Spring Dev Day 의 5대 발표 요약. Realtime API GA, Custom GPTs 수익화 GA, Computer Use 베타, Memory 표준 API, Voice agents. Realtime API 의 응답 지연 200ms 가 가장 호평.",
    content: "",
    category: "ai",
    image_url: "/card-news/openai-dev-day-spring-recap.png",
    external_link: "https://openai.com/blog/devday-spring-2026",
    tags: ["OpenAI", "DevDay", "Realtime"],
    created_at: "2026-05-15",
    span: "",
  },
  {
    id: 43,
    slug: "toss-frontend-architecture-2026",
    title: "토스 프론트엔드 — 2026 아키텍처 회고와 '왜 Remix 가 아니라 Next 였나'",
    summary: "토스 프론트엔드팀이 2026 아키텍처 회고를 공개했다. Remix 와 Next.js 사이에서 Next 를 택한 이유, SSR/CSR 비율 재조정, 그리고 모듈 페더레이션 폐기 결정까지. 결정의 근거가 명확해서 인기.",
    content: "",
    category: "dev",
    image_url: "/card-news/toss-frontend-architecture-2026.png",
    external_link: "https://toss.tech/article/frontend-architecture",
    tags: ["Toss", "Frontend", "Next.js"],
    created_at: "2026-05-14",
    span: "",
  },
  {
    id: 42,
    slug: "privacy-preserving-ai-techniques-survey",
    title: "프라이버시 보존 AI 기법 서베이 — DP·연합학습·TEE 의 실전 트레이드오프",
    summary: "MIT-IBM 공동 서베이가 프라이버시 보존 AI 의 세 축(Differential Privacy / Federated Learning / Trusted Execution Env)의 실전 성능을 비교. '하나만 쓰지 마라'가 결론. 의료·금융 도입 가이드 함께.",
    content: "",
    category: "trend",
    image_url: "/card-news/privacy-preserving-ai-techniques-survey.png",
    external_link: "https://arxiv.org/list/cs.CR/recent",
    tags: ["프라이버시", "연합학습", "DP"],
    created_at: "2026-05-13",
    span: "",
  },
  {
    id: 41,
    slug: "naver-hyperclova-x-2",
    title: "네이버 HyperCLOVA X 2.0 — 코드·수학 전용 변형 분리 출시",
    summary: "네이버가 HyperCLOVA X 2.0 를 발표했다. 범용 모델 외에 코드 전용(X-Coder)·수학 전용(X-Math) 변형을 분리. 한국어 코딩 벤치마크 자체 데이터셋도 함께 공개. NCloud 사용자 무료 일부 제공.",
    content: "",
    category: "ai",
    image_url: "/card-news/naver-hyperclova-x-2.png",
    external_link: "https://clova.ai/hyperclova",
    tags: ["네이버", "HyperCLOVA", "한국어AI"],
    created_at: "2026-05-12",
    span: "",
  },
  {
    id: 40,
    slug: "ai-music-billboard-rule",
    title: "Billboard, AI 생성 음악 차트 진입 규칙 명문화 — '인간 창작 비중 50% 이상'",
    summary: "Billboard 가 AI 음악 차트 등재 가이드라인을 공식화했다. '인간 작곡·작사·편곡 기여도 50% 이상 증빙'이 핵심. RIAA 와의 협의 결과. 가상 가수 시장에는 큰 영향 없을 전망.",
    content: "",
    category: "news",
    image_url: "/card-news/ai-music-billboard-rule.png",
    external_link: "https://www.billboard.com/",
    tags: ["AI음악", "Billboard", "저작권"],
    created_at: "2026-05-11",
    span: "",
  },
  {
    id: 39,
    slug: "gpu-secondary-market-crash",
    title: "H100 세컨더리 시장 30% 급락 — '훈련 GPU 잉여' 시그널?",
    summary: "H100 SXM 모듈의 세컨더리(중고) 가격이 1분기 대비 30% 급락. 클라우드 슬랏 가용성도 늘었다. 시장은 '훈련용 GPU 잉여' 신호인지, '단순 재고 조정'인지 의견 분분.",
    content: "",
    category: "trend",
    image_url: "/card-news/gpu-secondary-market-crash.png",
    external_link: "https://semianalysis.com/",
    tags: ["GPU", "H100", "시장"],
    created_at: "2026-05-10",
    span: "",
  },
  {
    id: 38,
    slug: "react-native-new-arch-default",
    title: "React Native 0.78 — New Architecture 가 기본값, Hermes 도 강제",
    summary: "React Native 0.78 부터 Fabric + TurboModules 가 default. Hermes 엔진도 강제. 1년 마이그레이션 준비 기간 끝. 미마이그레이션 앱은 'legacy mode' 로 격리되고 신규 기능 제한됨.",
    content: "",
    category: "dev",
    image_url: "/card-news/react-native-new-arch-default.png",
    external_link: "https://reactnative.dev/blog",
    tags: ["ReactNative", "Fabric", "Hermes"],
    created_at: "2026-05-09",
    span: "",
  },
  {
    id: 37,
    slug: "reasoning-model-tool-use-record",
    title: "Reasoning 모델 + Tool Use 동시 활성화 — Frontier 벤치마크 또 갱신",
    summary: "최신 Reasoning 모델들이 Tool Use 와 동시 활성화될 때 GPQA Diamond·MATH-500·OSWorld 까지 전부 SOTA 갱신. '도구 없는 추론'과 '추론 없는 도구'의 시대가 끝나간다.",
    content: "",
    category: "ai",
    image_url: "/card-news/reasoning-model-tool-use-record.png",
    external_link: "https://gpqa.io/",
    tags: ["Reasoning", "도구사용", "벤치마크"],
    created_at: "2026-05-08",
    span: "",
  },
  {
    id: 36,
    slug: "anthropic-computer-use-case-study",
    title: "Anthropic 발표 — Computer Use 가 RPA 라이센스 80% 줄인 보험사 사례",
    summary: "Anthropic 이 글로벌 보험사의 Computer Use 도입 사례를 공식 공개. 기존 UiPath/Blue Prism 라이센스 비용 80% 절감, 동시에 새 워크플로 도입 속도는 5배 빨라졌다. RPA 산업 재편의 기점.",
    content: "",
    category: "trend",
    image_url: "/card-news/anthropic-computer-use-case-study.png",
    external_link: "https://www.anthropic.com/customers",
    tags: ["Anthropic", "RPA", "도입사례"],
    created_at: "2026-05-07",
    span: "",
  },
  {
    id: 35,
    slug: "vercel-ai-sdk-v4-agentic",
    title: "Vercel AI SDK v4 — 에이전트 워크플로 정식 지원, 'streamText 만으론 끝'",
    summary: "Vercel 이 AI SDK v4 를 출시했다. 멀티스텝 에이전트 워크플로, 도구 호출 그래프, 사람 개입(human-in-the-loop) 패턴 모두 정식 API. AI 앱 개발의 새 베이스라인.",
    content: "",
    category: "dev",
    image_url: "/card-news/vercel-ai-sdk-v4-agentic.png",
    external_link: "https://sdk.vercel.ai/",
    tags: ["Vercel", "AISDK", "에이전트"],
    created_at: "2026-05-06",
    span: "",
  },
  {
    id: 34,
    slug: "kakao-honeybee-2",
    title: "카카오 Honeybee 2.0 — 한국어 멀티모달 모델, 자체 GPU 클러스터에서 학습",
    summary: "카카오가 Honeybee 2.0 멀티모달 모델 학습 완료를 알렸다. 자체 H100 1024장 클러스터에서 학습. KorOCR·KorVQA 벤치마크 SOTA. 카카오톡 챗봇·콜센터 통합이 1차 상용화 타깃.",
    content: "",
    category: "ai",
    image_url: "/card-news/kakao-honeybee-2.png",
    external_link: "https://tech.kakao.com/",
    tags: ["카카오", "Honeybee", "한국어AI"],
    created_at: "2026-05-05",
    span: "",
  },
  {
    id: 33,
    slug: "swe-bench-verified-1000",
    title: "SWE-bench Verified 1000 — 코딩 모델 사상 첫 95% 돌파, 인간 평균 추월",
    summary: "확장된 SWE-bench Verified 1000 에서 한 모델(미공개)이 95.2% 를 기록. 인간 시니어 엔지니어 평균(93%)을 처음으로 추월. 평가 환경 격리·재현성에 대한 검증은 진행 중.",
    content: "",
    category: "ai",
    image_url: "/card-news/swe-bench-verified-1000.png",
    external_link: "https://www.swebench.com/",
    tags: ["벤치마크", "SWE", "코딩AI"],
    created_at: "2026-05-04",
    span: "",
  },
  {
    id: 32,
    slug: "xai-grok-4-multimodal",
    title: "xAI Grok 4 — 멀티모달 추가, X 실시간 컨텍스트가 진짜 차별점",
    summary: "xAI 가 Grok 4 를 공개했다. 이미지·영상·실시간 X(트위터) 컨텍스트 통합. 벤치마크는 GPT-5·Claude Sonnet 4.5 와 동급. 차별점은 '지금 이 순간 트렌드' 에 대한 응답 정확도.",
    content: "",
    category: "ai",
    image_url: "/card-news/xai-grok-4-multimodal.png",
    external_link: "https://x.ai/",
    tags: ["xAI", "Grok", "Musk"],
    created_at: "2026-05-03",
    span: "",
  },
  {
    id: 31,
    slug: "karpathy-anthropic-pretraining",
    title: "Karpathy, Anthropic 사전학습팀 합류 — '재귀적 자가 개선' 라인업 완성?",
    summary: "Andrej Karpathy 가 Anthropic 사전학습팀 합류를 발표했다. Nick Joseph 휘하에서 'Claude 가 Claude 사전학습을 가속하는' 라인을 이끌 예정. OpenAI 이탈 3번째 시니어이자 강력한 시그널.",
    content: "",
    category: "ai",
    image_url: "/card-news/karpathy-anthropic-pretraining.png",
    external_link: "https://www.reddit.com/r/ClaudeAI/comments/1thw3bu/openai_cofounder_andrej_karpathy_just_joined/",
    tags: ["Karpathy", "Anthropic", "사전학습"],
    created_at: "2026-05-02",
    span: "",
  },
  {
    id: 30,
    slug: "toss-android-modularization",
    title: "토스 안드로이드 모듈화 — 200개 모듈 빌드 시간 1/3로 줄인 비법",
    summary: "토스 안드로이드팀이 200개 이상 모듈 구조에서 빌드 시간을 1/3 로 줄인 경험을 공유했다. KSP + Composite Build 조합, 그리고 의존성 그래프 정적 분석이 핵심. 코드 자체보다 그래프 모양을 먼저 본다.",
    content: "",
    category: "dev",
    image_url: "/card-news/toss-android-modularization.png",
    external_link: "https://toss.tech/",
    tags: ["Toss", "Android", "빌드"],
    created_at: "2026-05-01",
    span: "",
  },
  {
    id: 29,
    slug: "copilot-workspace-ga",
    title: "GitHub Copilot Workspace GA — '이슈 → PR' 풀 사이클 자동화",
    summary: "GitHub 가 Copilot Workspace 의 GA 를 알렸다. 이슈 → 명세 → 계획 → 구현 → 테스트 → PR 까지 풀 사이클 자동화. 엔터프라이즈 시트 비용은 월 39 달러, Pro 는 19 달러.",
    content: "",
    category: "dev",
    image_url: "/card-news/copilot-workspace-ga.png",
    external_link: "https://github.com/features/copilot",
    tags: ["GitHub", "Copilot", "에이전트"],
    created_at: "2026-04-30",
    span: "",
  },
  {
    id: 28,
    slug: "eu-ai-act-first-fine",
    title: "EU AI Act 첫 과징금 부과 — 채용 AI 운영사에 2700만 유로",
    summary: "EU 가 AI Act 시행 후 첫 과징금을 부과했다. 채용 자동화 AI 운영사가 '고위험 시스템 영향평가 미실시'로 2700만 유로(약 400억원). 미국·아시아 기업의 EU 운영 시 컴플라이언스 비용 재계산 중.",
    content: "",
    category: "news",
    image_url: "/card-news/eu-ai-act-first-fine.png",
    external_link: "https://digital-strategy.ec.europa.eu/en/policies/ai-act",
    tags: ["EU", "AIAct", "과징금"],
    created_at: "2026-04-29",
    span: "",
  },
  {
    id: 27,
    slug: "huggingface-spaces-100k-apps",
    title: "HuggingFace Spaces 10만 앱 돌파 — '비개발자 AI 빌더' 비중 35%",
    summary: "HuggingFace 가 Spaces 누적 10만 앱 돌파를 알렸다. 신규 앱 중 35% 가 'no-code/low-code' 카테고리. Gradio + Claude/GPT 결합 워크플로가 비개발자 진입 장벽을 크게 낮췄다.",
    content: "",
    category: "trend",
    image_url: "/card-news/huggingface-spaces-100k-apps.png",
    external_link: "https://huggingface.co/spaces",
    tags: ["HuggingFace", "Gradio", "노코드"],
    created_at: "2026-04-28",
    span: "",
  },
  {
    id: 26,
    slug: "python-313-free-threading-real",
    title: "Python 3.13 free-threading 실전 — NumPy·PyTorch 호환 매트릭스 공개",
    summary: "Python 3.13t (free-threading) 의 주요 과학 라이브러리 호환 매트릭스가 공식 정리됐다. NumPy 2.2·PyTorch 2.5 모두 'compatible'. GIL 없는 멀티스레딩이 데이터 사이언스 영역에서 본격 시동.",
    content: "",
    category: "dev",
    image_url: "/card-news/python-313-free-threading-real.png",
    external_link: "https://py-free-threading.github.io/",
    tags: ["Python", "GIL", "동시성"],
    created_at: "2026-04-27",
    span: "",
  },
  {
    id: 25,
    slug: "tesla-fsd-v14-supervised",
    title: "Tesla FSD v14 — 'Supervised' 라벨 유지, 그러나 개입 빈도 10배 감소",
    summary: "Tesla FSD v14 가 배포됐다. NHTSA 와의 합의로 'Supervised' 라벨은 유지되지만, 사용자 보고 평균 개입 빈도는 v13 대비 10배 줄었다. 머스크는 unsupervised 데모를 2026 하반기 예고.",
    content: "",
    category: "news",
    image_url: "/card-news/tesla-fsd-v14-supervised.png",
    external_link: "https://www.tesla.com/AI",
    tags: ["Tesla", "자율주행", "FSD"],
    created_at: "2026-04-26",
    span: "",
  },
  {
    id: 24,
    slug: "stable-diffusion-4-photoreal",
    title: "Stable Diffusion 4 — 포토리얼리즘 격차 거의 사라졌다",
    summary: "Stability AI 가 SD4 를 공개. ELO 점수에서 Midjourney v7 과 통계적 유의차가 사라졌다. 라이선스는 여전히 상업 사용 시 구독 필요. 오픈 가중치는 비상업 한정.",
    content: "",
    category: "ai",
    image_url: "/card-news/stable-diffusion-4-photoreal.png",
    external_link: "https://stability.ai/",
    tags: ["StableDiffusion", "이미지생성", "Stability"],
    created_at: "2026-04-25",
    span: "",
  },
  {
    id: 23,
    slug: "apple-intelligence-eu-rollout",
    title: "Apple Intelligence 유럽 출시 — DMA 협상 1년 만에 합의",
    summary: "Apple Intelligence 가 EU 에서 정식 출시. DMA(디지털시장법) 와의 충돌로 지연됐던 협상이 마무리됐다. 단, 일부 기능(Genmoji 일부)은 EU 한정으로 제외.",
    content: "",
    category: "news",
    image_url: "/card-news/apple-intelligence-eu-rollout.png",
    external_link: "https://www.apple.com/apple-intelligence/",
    tags: ["Apple", "EU", "DMA"],
    created_at: "2026-04-24",
    span: "",
  },
  {
    id: 22,
    slug: "korea-ai-startup-series-c-flood",
    title: "국내 AI 스타트업 시리즈 C 봇물 — Q1 누적 8000억원 돌파",
    summary: "국내 AI 스타트업의 시리즈 C+ 투자가 1분기에만 8000억원을 넘겼다. 업스테이지·뤼튼·트웰브랩스가 견인. 'AI 겨울 끝났다'는 평가와 'B2B SaaS 외엔 갈 곳 없다'는 회의론이 공존.",
    content: "",
    category: "news",
    image_url: "/card-news/korea-ai-startup-series-c-flood.png",
    external_link: "https://platum.kr/archives/series-c",
    tags: ["스타트업", "투자", "한국"],
    created_at: "2026-04-23",
    span: "",
  },
  {
    id: 21,
    slug: "computer-use-2-screen-grounding",
    title: "Anthropic Computer Use 2 — 스크린 grounding 정확도 90% 돌파",
    summary: "Anthropic 이 Computer Use 의 후속 버전을 공개했다. UI 요소 좌표 추론(grounding) 정확도가 OSWorld 벤치마크에서 90% 를 넘어섰다. RPA 업계가 '대대적 재편' 우려 중.",
    content: "",
    category: "ai",
    image_url: "/card-news/computer-use-2-screen-grounding.png",
    external_link: "https://www.anthropic.com/research/computer-use",
    tags: ["Anthropic", "ComputerUse", "RPA"],
    created_at: "2026-04-22",
    span: "",
  },
  {
    id: 20,
    slug: "mcp-protocol-w3c-track",
    title: "Model Context Protocol — W3C 표준화 트랙 진입, 멀티벤더 호환성 가시화",
    summary: "Anthropic 이 만든 MCP(Model Context Protocol)가 W3C Community Group 단계를 거쳐 표준화 트랙에 올랐다. OpenAI·Google 도 자사 구현체로 참여 의사 표명. 도구 호출 표준이 곧 통일된다.",
    content: "",
    category: "ai",
    image_url: "/card-news/mcp-protocol-w3c-track.png",
    external_link: "https://modelcontextprotocol.io/",
    tags: ["MCP", "표준", "W3C"],
    created_at: "2026-04-21",
    span: "",
  },
  {
    id: 19,
    slug: "react-19-server-actions-patterns",
    title: "React 19 Server Actions 패턴 모음 — Form 외 영역에서도 활용 가능",
    summary: "React 코어팀이 Server Actions 의 비 Form 활용 패턴(검색, 페이지네이션, 낙관적 업데이트)을 정리한 공식 가이드를 발표했다. RSC + Action 조합이 데이터 페칭의 새 표준으로 자리잡는 분위기.",
    content: "",
    category: "dev",
    image_url: "/card-news/react-19-server-actions-patterns.png",
    external_link: "https://react.dev/reference/rsc/server-actions",
    tags: ["React", "ServerActions", "RSC"],
    created_at: "2026-04-20",
    span: "",
  },
  {
    id: 18,
    slug: "ai-agents-enterprise-adoption-curve",
    title: "AI 에이전트 엔터프라이즈 도입 — 'PoC 80%, 프로덕션 12%' 의 골짜기",
    summary: "McKinsey 의 2026 1분기 조사. 글로벌 대기업 중 80%가 AI 에이전트 PoC 를 돌렸지만 프로덕션 배포는 12%에 불과. 가장 큰 장벽은 '책임 소재 불명확'과 '감사 추적 미흡'.",
    content: "",
    category: "trend",
    image_url: "/card-news/ai-agents-enterprise-adoption-curve.png",
    external_link: "https://www.mckinsey.com/featured-insights/artificial-intelligence",
    tags: ["에이전트", "엔터프라이즈", "도입"],
    created_at: "2026-04-19",
    span: "",
  },
  {
    id: 17,
    slug: "typescript-56-using-keyword",
    title: "TypeScript 5.6 — 'using' 키워드 stable, 리소스 자동 해제가 언어 기본이 된다",
    summary: "TypeScript 5.6 RC 에서 ECMAScript Explicit Resource Management 가 정식 지원으로 승격. 파일 핸들·DB 연결 같은 리소스를 try-finally 없이 자동 해제 가능. Node.js 24 와 함께 쓰면 효과 극대화.",
    content: "",
    category: "dev",
    image_url: "/card-news/typescript-56-using-keyword.png",
    external_link: "https://devblogs.microsoft.com/typescript/",
    tags: ["TypeScript", "ES2026", "리소스"],
    created_at: "2026-04-18",
    span: "",
  },
  {
    id: 16,
    slug: "woowahan-jpa-event-sourcing",
    title: "우아한형제들 — JPA 만으로 이벤트 소싱 구현한 결제 시스템 회고",
    summary: "배달의민족 결제팀이 별도 ES 프레임워크 없이 JPA + 이벤트 테이블 패턴만으로 이벤트 소싱을 구현한 경험을 공유했다. Axon·Eventuate 없이도 도메인 일관성을 지키는 실전 패턴이 핵심.",
    content: "",
    category: "dev",
    image_url: "/card-news/woowahan-jpa-event-sourcing.png",
    external_link: "https://techblog.woowahan.com/",
    tags: ["우아한형제들", "JPA", "이벤트소싱"],
    created_at: "2026-04-17",
    span: "",
  },
  {
    id: 15,
    slug: "meta-llama-4-405b-open",
    title: "Meta Llama 4 405B 공개 — 오픈 가중치 그대로, 로컬 추론 한계가 또 밀렸다",
    summary: "Meta 가 Llama 4 의 405B 변형을 오픈 가중치로 공개했다. 양자화 4bit 기준 단일 H100 80GB 두 대로 추론 가능. r/LocalLLaMA 에서는 '드디어 GPT-4o 대안이 손에 들어왔다' 는 반응.",
    content: "",
    category: "ai",
    image_url: "/card-news/meta-llama-4-405b-open.png",
    external_link: "https://ai.meta.com/llama/",
    tags: ["Llama", "Meta", "오픈소스"],
    created_at: "2026-04-16",
    span: "",
  },
  {
    id: 14,
    slug: "gemini-25-pro-multimodal-leap",
    title: "Gemini 2.5 Pro — 멀티모달 추론에서 GPT-5o 와 정면 비교 데이터 등장",
    summary: "Google DeepMind 가 Gemini 2.5 Pro 의 멀티모달 평가 결과를 공개했다. 영상·오디오·차트 이해 카테고리에서 GPT-5o 와 1-2점 차이의 박빙. 100만 토큰 컨텍스트 윈도우는 여전한 차별점.",
    content: "",
    category: "ai",
    image_url: "/card-news/gemini-25-pro-multimodal-leap.png",
    external_link: "https://deepmind.google/technologies/gemini/",
    tags: ["Gemini", "Google", "멀티모달"],
    created_at: "2026-04-15",
    span: "",
  },
  {
    id: 13,
    slug: "nvidia-blackwell-ultra-shipping",
    title: "NVIDIA Blackwell Ultra 공급 시작 — 하이퍼스케일러 우선 배정",
    summary: "NVIDIA 가 Blackwell Ultra(B300) GPU 의 본격 출하를 알렸다. 초기 물량의 70% 이상이 AWS·Azure·GCP·Oracle 등 하이퍼스케일러로 배정. 한국 기업은 2026년 하반기부터 접근 가능할 것으로 전망.",
    content: "",
    category: "news",
    image_url: "/card-news/nvidia-blackwell-ultra-shipping.png",
    external_link: "https://nvidianews.nvidia.com/",
    tags: ["NVIDIA", "GPU", "B300"],
    created_at: "2026-04-14",
    span: "",
  },
  {
    id: 12,
    slug: "korea-ai-basic-act-effect",
    title: "한국 AI 기본법 시행 1년 — '고영향 AI' 기업 절반 컴플라이언스 미흡",
    summary: "AI 기본법 시행 1주년 점검 결과, 고영향 AI 서비스 운영 기업의 절반 가까이가 영향평가·투명성 의무를 제대로 이행하지 못한 것으로 드러났다. 과기정통부는 후반기 시정 명령을 예고했다.",
    content: "",
    category: "news",
    image_url: "/card-news/korea-ai-basic-act-effect.png",
    external_link: "https://www.korea.kr/news/policyNewsView.do",
    tags: ["AI규제", "한국", "컴플라이언스"],
    created_at: "2026-04-13",
    span: "",
  },
  {
    id: 11,
    slug: "nextjs-16-ppr-ga",
    title: "Next.js 16 GA — Partial Prerendering 정식 출시, App Router 가 표준 된다",
    summary: "Vercel 이 Next.js 16 정식 버전을 출시했다. PPR(Partial Prerendering)이 default 로 켜지며 정적 셸 + 동적 콘텐츠 분리가 자동화됨. Pages Router 는 deprecation 카운트다운 시작.",
    content: "",
    category: "dev",
    image_url: "/card-news/nextjs-16-ppr-ga.png",
    external_link: "https://nextjs.org/blog/next-16",
    tags: ["Next.js", "Vercel", "PPR"],
    created_at: "2026-04-12",
    span: "",
  },
  {
    id: 10,
    slug: "claude-sonnet-45-extended-thinking",
    title: "Claude Sonnet 4.5 — Extended Thinking 자동 활성화, 코딩 정확도 또 상승",
    summary: "Anthropic 이 Sonnet 4.5 에서 Extended Thinking 을 자동 트리거하도록 업데이트했다. 복잡도 임계치 넘으면 자동으로 사고 체인 확장. SWE-bench Verified 에서 또 한 차례 점수 상승 보고됨.",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-sonnet-45-extended-thinking.png",
    external_link: "https://www.anthropic.com/news",
    tags: ["Claude", "Anthropic", "코딩"],
    created_at: "2026-04-11",
    span: "",
  },
  {
    id: 9,
    slug: "gpt5-dev-day-roadmap",
    title: "OpenAI Dev Day 2026 — GPT-5 로드맵 공개, '에이전트 OS'가 핵심",
    summary: "OpenAI 가 봄철 Dev Day 에서 GPT-5 를 단순 모델이 아닌 '에이전트 OS' 로 포지셔닝했다. Computer Use API 통합, 메모리·도구 표준화, 그리고 멀티 에이전트 오케스트레이션이 키노트 주제. 개발자들은 ChatGPT 의존도가 낮아질 것을 기대 중.",
    content: "",
    category: "ai",
    image_url: "/card-news/gpt5-dev-day-roadmap.png",
    external_link: "https://openai.com/devday",
    tags: ["OpenAI", "GPT-5", "에이전트"],
    created_at: "2026-04-10",
    span: "",
  },
  {
    id: 1,
    slug: "anthropic-claude-cowork-ga",
    title: "Claude Cowork 정식 출시 — Anthropic 데스크탑 에이전트, macOS·Windows GA",
    summary: "1월 리서치 프리뷰로 공개됐던 Anthropic 의 데스크탑 에이전트 Claude Cowork 가 macOS·Windows 정식 출시. RBAC, Group Spend Limit, OpenTelemetry, Zoom MCP 커넥터 등 엔터프라이즈 6종 기능 동시 탑재. 파일 접근·멀티스텝 실행·도구 통합을 그대로 데스크톱 UI 로 옮긴 형태.",
    content: "",
    category: "ai",
    image_url: "/card-news/anthropic-claude-cowork-ga.png",
    external_link: "https://9to5mac.com/2026/04/09/anthropic-scales-up-with-enterprise-features-for-claude-cowork-and-managed-agents/",
    tags: ["Claude", "Anthropic", "Cowork"],
    created_at: "2026-04-09",
    span: "",
  },
  {
    id: 2,
    slug: "anthropic-managed-agents-beta",
    title: "Anthropic Managed Agents 공개 베타 — Claude 에이전트 클라우드 호스팅",
    summary: "Anthropic 이 Cowork GA 발표와 같은 날 Managed Agents 를 공개 베타로 출시. 클라우드에서 호스팅되는 에이전트 형태로, 별도 인프라 없이 멀티 에이전트 워크플로 구축 가능. Claude Code 도 같은 날 정책 컨트롤 + Bedrock 셋업 마법사 추가로 엔터프라이즈 준비도 강화.",
    content: "",
    category: "ai",
    image_url: "/card-news/anthropic-managed-agents-beta.png",
    external_link: "https://www.testingcatalog.com/anthropic-launches-claude-cowork-in-general-availability/",
    tags: ["Anthropic", "Managed Agents", "에이전트"],
    created_at: "2026-04-09",
    span: "",
  },
  {
    id: 3,
    slug: "anthropic-project-glasswing-mythos",
    title: "Anthropic Project Glasswing — Mythos Preview, 수천 개 제로데이 자율 발견",
    summary: "Anthropic 이 Opus 상위 티어 모델 Mythos Preview 와 방어 전용 이니셔티브 Project Glasswing 공개. 모든 주요 OS·웹 플랫폼에서 수천 개의 high/critical zero-day 를 자율 발견 (99%+ 미패치 상태). OpenBSD TCP 스택 27년 묵은 취약점, FFmpeg H.264 코덱 16년 묵은 결함까지 적발. 일반 공개 대신 AWS·Apple·Google·MS·NVIDIA·Linux Foundation 등 40+ 파트너에 한정 제공.",
    content: "",
    category: "ai",
    image_url: "/card-news/anthropic-project-glasswing-mythos.png",
    external_link: "https://www.anthropic.com/glasswing",
    tags: ["Anthropic", "Mythos", "보안"],
    created_at: "2026-04-08",
    span: "",
  },
  {
    id: 4,
    slug: "eu-ai-act-omnibus-negotiation",
    title: "EU AI Act Omnibus — 고위험 AI 의무 2027.12 로 연기 협상 본격화",
    summary: "유럽위원회가 작년 11월 발의한 Digital Omnibus on AI 가 트릴로그 단계 진입. 고위험 AI 시스템(Annex III) 적용일을 2026.8.2 → 2027.12.2 로 연기하는 게 핵심. 의료기기·산업기계·완구·커넥티드카처럼 기존 EU 규제와 중첩되는 영역의 면제 여부가 쟁점. 협상 실패 시 원안 8.2 발효 가능성도 살아있어 컴플라이언스 팀 비상.",
    content: "",
    category: "news",
    image_url: "/card-news/eu-ai-act-omnibus-negotiation.png",
    external_link: "https://iapp.org/news/a/ai-act-omnibus-what-just-happened-and-what-comes-next",
    tags: ["EU", "AI규제", "Omnibus"],
    created_at: "2026-04-08",
    span: "",
  },
  {
    id: 5,
    slug: "google-veo-31-free-public-access",
    title: "Google Veo 3.1, 모든 Google 계정 무료 개방 — 월 10회 영상 생성",
    summary: "Google 이 Veo 3.1 을 모든 개인 Google 계정에 무료 개방. 월 10회 720p/8초 영상 + 1080p·4K 업스케일링 기능 함께 제공, 구독·신용카드 불필요. 4.7 에는 Veo 3.1 Fast 가격 인하 + Lite 모델 출시로 개발자용 비용도 절반 이하로 떨어짐. Vids.new 에서 즉시 사용 가능.",
    content: "",
    category: "ai",
    image_url: "/card-news/google-veo-31-free-public-access.png",
    external_link: "https://www.ghacks.net/2026/04/07/google-opens-veo-3-1-ai-video-generation-to-all-users-with-free-monthly-access/",
    tags: ["Veo3", "Google", "영상생성"],
    created_at: "2026-04-07",
    span: "",
  },
  {
    id: 6,
    slug: "nvidia-blackwell-ultra-platform",
    title: "NVIDIA Blackwell Ultra 발표 — GB300 NVL72, AI 추론 1.5배 향상",
    summary: "NVIDIA 가 GTC 2026 키노트 후속으로 Blackwell Ultra AI 팩토리 플랫폼을 공식 공개. GB300 NVL72 가 GB200 대비 AI 성능 1.5배, AI 팩토리 매출 기회 50배 (Hopper 대비). AWS·GCP·Azure·OCI 가 첫 인스턴스 제공 예정. Dynamo 오픈소스 추론 프레임워크 동시 공개로 reasoning AI 모델 배포 효율화.",
    content: "",
    category: "news",
    image_url: "/card-news/nvidia-blackwell-ultra-platform.png",
    external_link: "https://nvidianews.nvidia.com/news/nvidia-blackwell-ultra-ai-factory-platform-paves-way-for-age-of-ai-reasoning",
    tags: ["NVIDIA", "GPU", "Blackwell"],
    created_at: "2026-04-07",
    span: "",
  },
  {
    id: 7,
    slug: "frontier-model-forum-china-distillation",
    title: "OpenAI·Anthropic·Google, 중국 모델 카피 차단 — Frontier Model Forum 공동 대응",
    summary: "OpenAI·Anthropic·Google 이 Frontier Model Forum 채널을 통해 중국 경쟁사의 모델 distillation (adversarial 추출) 시도 정보를 실시간 공유하기로. 미국 프론티어 모델의 능력을 그대로 베끼는 사례가 늘면서, 평소 경쟁 관계인 회사들도 안보 명목으로 협업. AI 패권 경쟁의 새로운 국면이자 frontier 모델 IP 보호의 첫 공동 프레임워크.",
    content: "",
    category: "trend",
    image_url: "/card-news/frontier-model-forum-china-distillation.png",
    external_link: "https://www.bloomberg.com/news/articles/2026-04-06/openai-anthropic-google-unite-to-combat-model-copying-in-china",
    tags: ["Frontier Model Forum", "보안", "AI규제"],
    created_at: "2026-04-06",
    span: "",
  },
  {
    id: 8,
    slug: "broadcom-anthropic-tpu-3-5gw-deal",
    title: "Broadcom-Anthropic 3.5GW 칩 딜 — Google TPU 기반 컴퓨팅 확보",
    summary: "Broadcom 이 Anthropic 과 약 3.5GW 규모의 컴퓨팅 용량 공급 계약 확장 발표. Google 의 AI 프로세서(TPU) 기반 인프라를 Broadcom 이 중계하는 구조로, NVIDIA GPU 의존 일변도였던 AI 인프라 시장에 큰 균열을 내는 거래. 칩 공급망 다변화 추세 가속화 — AI 인프라 패권의 새 시즌 개막.",
    content: "",
    category: "news",
    image_url: "/card-news/broadcom-anthropic-tpu-3-5gw-deal.png",
    external_link: "https://www.cnbc.com/2026/04/06/broadcom-agrees-to-expanded-chip-deals-with-google-anthropic.html",
    tags: ["Broadcom", "Anthropic", "AI인프라"],
    created_at: "2026-04-06",
    span: "",
  },
  /* TECH-NEWS-PIPELINE-DATA:END */
];

export default function CardNewsPage() {
  return (
    <main className="pt-28 pb-24 px-6 md:px-10 max-w-6xl mx-auto">
      <PageHeading
        eyebrow="Card News · Reddit AI · Tech"
        count={CARD_NEWS_DATA.length}
        size="xl"
        title={
          <>
            What&apos;s<br />
            <span className="display-accent display-accent-coral">hot</span> today.
          </>
        }
        lead={
          <>
            Reddit <span className="text-em">r/artificial</span>,
            <span className="text-em"> r/technology</span>에서 엄선한 AI &amp; 기술 트렌드.
            클릭해서 요약과 원문 링크를 확인하세요.
          </>
        }
      />

      <CardNewsGallery items={CARD_NEWS_DATA} />
    </main>
  );
}
