import type { Metadata } from "next";
import CardNewsGallery, { type CardNewsItem } from "@/components/card-news/card-news-gallery";
import { PageHeading } from "@/components/section/page-heading";

export const metadata: Metadata = {
  title: "카드뉴스 | GoTechy",
  description: "Reddit r/artificial, r/technology에서 엄선한 AI & 기술 트렌드를 카드뉴스로 빠르게 만나보세요.",
  alternates: { canonical: "/card-news" },
};

/* Reddit AI/Tech 트렌드 기반 샘플 데이터 */
const CARD_NEWS_DATA: CardNewsItem[] = [
/* TECH-NEWS-PIPELINE-DATA:START */
  {
    id: 134,
    slug: "deepseek-v4-pro-0813-on-openrouter",
    title: "DeepSeek V4 Pro 0813 (on OpenRouter)",
    summary: "DeepSeek V4 Pro 0813 (on OpenRouter) The latest DeepSeek Pro model is now available, via API only. I had to link to OpenRouter because DeepSeek don't have any obvious announcement page for their new model. I haven't been able to confirm if ",
    content: "",
    category: "news",
    image_url: "/card-news/deepseek-v4-pro-0813-on-openrouter.png",
    external_link: "https://simonwillison.net/2026/Aug/12/deepseek-v4-pro-0813/",
    tags: ["DeepSeek", "Pro", "OpenRouter"],
    created_at: "2026-08-13",
    span: "",
  },
  {
    id: 133,
    slug: "introducing-unsloth-desktop-app",
    title: "Introducing Unsloth Desktop app",
    summary: "Hi LocalLlama, we're super excited to release Unsloth Desktop today! 🦥 It's the first desktop app that enables you to run and train models locally. Open-source. Available on Mac, Windows, and Linux Supports MLX, diffusion image/video models",
    content: "",
    category: "news",
    image_url: "/card-news/introducing-unsloth-desktop-app.png",
    external_link: "https://v.redd.it/i8b4n5ddbrih1",
    tags: ["Introducing", "Unsloth", "Desktop"],
    created_at: "2026-08-12",
    span: "",
  },
  {
    id: 132,
    slug: "introducing-muse-glimmer-an-open-weight-model-optimized-for-",
    title: "Introducing Muse Glimmer: an open-weight model optimized for always-on local agent workflows",
    summary: "Hi r/LocalLLaMA 👋 Today we’re excited to release Muse Glimmer, a 30B open-weight model built specifically for local agent workflows. We’re releasing the weights to the community under a permissive Apache 2.0 license. A few specs 30B params,",
    content: "",
    category: "news",
    image_url: "/card-news/introducing-muse-glimmer-an-open-weight-model-optimized-for-.png",
    external_link: "https://www.reddit.com/gallery/1vkgsum",
    tags: ["Introducing", "Muse", "Glimmer"],
    created_at: "2026-08-11",
    span: "",
  },
  {
    id: 131,
    slug: "the-gemma-team-will-host-a-special-event-on-august-20",
    title: "The Gemma team will host a special event on August 20",
    summary: "Tweet by u/hackerllama Could be copium, but I would love to see Gemma 4.1 there with unified audio input for all model sizes perhaps even up to 120B, much improved tool calling (even with the latest template there are still bugs ), higher p",
    content: "",
    category: "news",
    image_url: "/card-news/the-gemma-team-will-host-a-special-event-on-august-20.png",
    external_link: "https://x.com/osanseviero/status/2086107547535122767",
    tags: ["The", "Gemma", "August"],
    created_at: "2026-08-10",
    span: "",
  },
  {
    id: 130,
    slug: "claude-code-your-sessions-can-now-message-each-other",
    title: "Claude code : your sessions can now message each other.",
    summary: "With Claude Code v2.1.224 introducing cross-session messaging (agents syncing backend/frontend tasks independently), how do you plan to change your multi-terminal setup? Are you ready to let agents hand off context to each other?",
    content: "",
    category: "news",
    image_url: "/card-news/claude-code-your-sessions-can-now-message-each-other.png",
    external_link: "https://www.reddit.com/gallery/1vio0w9",
    tags: ["Claude"],
    created_at: "2026-08-09",
    span: "",
  },
  {
    id: 129,
    slug: "got-job-as-director-of-ai-and-systems-development-self-taugh",
    title: "Got job as Director of AI and Systems development self-taught",
    summary: "Hey everyone, I just wanted to share my journey here for some motivation. Three years ago, I saw the sudden spike in AI and realized it was the future of tech. My goal at the time was to be an indie game dev, and seeing that AI could write ",
    content: "",
    category: "news",
    image_url: "/card-news/got-job-as-director-of-ai-and-systems-development-self-taugh.png",
    external_link: "https://www.reddit.com/r/LocalLLaMA/comments/1vi8jlr/got_job_as_director_of_ai_and_systems_development/",
    tags: ["Got", "Director", "AI"],
    created_at: "2026-08-08",
    span: "",
  },
  {
    id: 128,
    slug: "top-15-mcp-servers-that-are-actually-useful-in-2026-im-tired",
    title: "Top 15+ MCP servers that are actually useful in 2026? I’m tired of fake awesome lists",
    summary: "I’m trying to clean up my MCP setup and honestly I’m lost. Every best MCP servers list looks like SEO garbage now. Half the tools are abandoned, half need weird auth, and half sound useful until you actually plug them into Claude/Cursor/Cod",
    content: "",
    category: "news",
    image_url: "/card-news/top-15-mcp-servers-that-are-actually-useful-in-2026-im-tired.png",
    external_link: "https://www.reddit.com/r/ClaudeAI/comments/1vh0yd3/top_15_mcp_servers_that_are_actually_useful_in/",
    tags: ["Top", "MCP"],
    created_at: "2026-08-07",
    span: "",
  },
  {
    id: 127,
    slug: "i-built-a-captioning-app-for-short-form-video-then-gave-clau",
    title: "I built a captioning app for short-form video, then gave Claude an MCP so it can work with captions alone",
    summary: "Hi all. I built CapForge, a local app that transcribes video and burns animated captions over it. I made it because every cloud captioning tool I tried was subscription based and I did not want to upload unreleased footage to someone else's",
    content: "",
    category: "news",
    image_url: "/card-news/i-built-a-captioning-app-for-short-form-video-then-gave-clau.png",
    external_link: "https://v.redd.it/uw02v5i6uihh1",
    tags: ["Claude", "MCP"],
    created_at: "2026-08-06",
    span: "",
  },
  {
    id: 126,
    slug: "new-release-of-llm-adds-support-for-reasoning-traces-openai-",
    title: "New release of LLM adds support for reasoning traces, OpenAI Responses, server-side tools, and smarter logging",
    summary: "I released LLM 0.32 this morning, the most significant new version of LLM since the initial launch of the project. The new version includes support for visible reasoning traces, server-side provider tools, redesigned content-addressable SQL",
    content: "",
    category: "news",
    image_url: "/card-news/new-release-of-llm-adds-support-for-reasoning-traces-openai-.png",
    external_link: "https://simonwillison.net/2026/Aug/4/new-release-of-llm/#atom-everything",
    tags: ["New", "LLM", "OpenAI"],
    created_at: "2026-08-05",
    span: "",
  },
  {
    id: 125,
    slug: "open-always-wins-how-china-is-using-the-open-source-playbook",
    title: "Open always wins: How China is using the open source playbook to dominate AI's next chapter",
    summary: "The United States built its tech dominance on one principle: Open beats closed. Now China is using that playbook to shape AI's future. Consider: The performance gap between the leading American and Chinese models has narrowed to single digi",
    content: "",
    category: "ai",
    image_url: "/card-news/open-always-wins-how-china-is-using-the-open-source-playbook.png",
    external_link: "https://www.reddit.com/r/artificial/comments/1vejxnd/open_always_wins_how_china_is_using_the_open/",
    tags: ["Open", "How", "China"],
    created_at: "2026-08-04",
    span: "",
  },
  {
    id: 124,
    slug: "i-pushed-kimi-k3-onto-one-cpu-with-8-gb-of-ram",
    title: "I pushed Kimi K3 onto one CPU with 8 GB of RAM",
    summary: "I deployed K3 on 32 H100s at work a couple of weeks ago and then got annoyed that there was no way to poke at it on my own machine . So I wrote an inference engine for it in C99. Nothing clever going on. 93% of that 1.56 TB checkpoint is ro",
    content: "",
    category: "news",
    image_url: "/card-news/i-pushed-kimi-k3-onto-one-cpu-with-8-gb-of-ram.png",
    external_link: "https://www.reddit.com/r/LocalLLaMA/comments/1vd874t/i_pushed_kimi_k3_onto_one_cpu_with_8_gb_of_ram/",
    tags: ["Kimi", "CPU", "GB"],
    created_at: "2026-08-03",
    span: "",
  },
  {
    id: 123,
    slug: "stateless-mcp-has-recaptured-my-interest-and-inspired-mcp-ex",
    title: "Stateless MCP has recaptured my interest (and inspired mcp-explorer and datasette-mcp)",
    summary: "Tuesday was Stateless MCP day - the rollout of MCP 2.0, or the 2026-07-28 Model Context Protocol specification to use the more formal but less memorable name. This is the most significant change to the MCP spec since it first launched, and ",
    content: "",
    category: "news",
    image_url: "/card-news/stateless-mcp-has-recaptured-my-interest-and-inspired-mcp-ex.png",
    external_link: "https://simonwillison.net/2026/Jul/31/stateless-mcp/#atom-everything",
    tags: ["Stateless", "MCP"],
    created_at: "2026-08-02",
    span: "",
  },
  {
    id: 122,
    slug: "deepseek-v4-flash-has-been-updated-the-official-release-of-d",
    title: "DeepSeek-V4-Flash has been updated, \"The official release of DeepSeek-V4-Pro will follow soon\"",
    summary: "https://api-docs.deepseek.com/updates/ Edit: official post on 𝕏: https://x.com/deepseek_ai/status/2083084415157022911",
    content: "",
    category: "news",
    image_url: "/card-news/deepseek-v4-flash-has-been-updated-the-official-release-of-d.png",
    external_link: "https://i.redd.it/mbz7sdwbaigh1.jpeg",
    tags: ["DeepSeek", "Flash", "The"],
    created_at: "2026-08-01",
    span: "",
  },
  {
    id: 121,
    slug: "llm-032rc2",
    title: "llm 0.32rc2",
    summary: "Release: llm 0.32rc2 Hot on the heels of RC1, this fixes a dependency issue and also adds two neat new features: The default model for users who have not set their own default is now GPT-5.6 Luna. It was previously GPT-4o mini. Luna is a mu",
    content: "",
    category: "news",
    image_url: "/card-news/llm-032rc2.png",
    external_link: "https://simonwillison.net/2026/Jul/30/llm-rc2/#atom-everything",
    tags: ["AI", "기술", "트렌드"],
    created_at: "2026-07-31",
    span: "",
  },
  {
    id: 120,
    slug: "how-enabling-two-settings-tripled-our-scores-on-the-arc-agi-",
    title: "How enabling two settings tripled our scores on the ARC-AGI-3 benchmark",
    summary: "How two API settings improved GPT-5.6 performance on ARC-AGI-3, boosting scores and efficiency by retaining reasoning and enabling compaction.",
    content: "",
    category: "news",
    image_url: "/card-news/how-enabling-two-settings-tripled-our-scores-on-the-arc-agi-.png",
    external_link: "https://openai.com/index/how-two-settings-tripled-our-arc-agi-3-scores",
    tags: ["How", "ARC", "AGI"],
    created_at: "2026-07-30",
    span: "",
  },
  {
    id: 68,
    slug: "더-작고-강해진-kanana-slm-개발",
    title: "더 작고 강해진 Kanana SLM 개발",
    summary: "안녕하세요. 카카오의 AI 모델 개발을 담당하는 카나나 LLM 조직에서 언어모델을 개발하고 있는 Kaya, Ryan, Wavy 입니다. 지난 “작지만 강한 Kanana Nano 효율적으로 개발하기”에서 비용 효율적으로 SLM(Small Language Model)을 개발하는 방법에 대해서 소개드렸었는데요, 이번 글에서는 더 강력해져서 돌아온 카카오의 두 번째 SLM 시리즈를 소개드리고자 합니다. 이번에 소개해드릴 모델은 Kan",
    content: "",
    category: "news",
    image_url: "/card-news/더-작고-강해진-kanana-slm-개발.png",
    external_link: "https://tech.kakao.com/posts/826",
    tags: ["Kanana", "SLM"],
    created_at: "2026-07-28",
    span: "",
  },
  {
    id: 69,
    slug: "the-chinese-labs-everyone-lumps-together-are-making-four-pre",
    title: "The Chinese labs everyone lumps together are making four pretty different bets",
    summary: "Still composing my thoughts, i will edit thisEvery time a model drops from a Chinese lab the thread fills with people who already know who made it, and the guess is usually Alibaba. There was a thread here recently asking what separates the",
    content: "",
    category: "news",
    image_url: "/card-news/the-chinese-labs-everyone-lumps-together-are-making-four-pre.png",
    external_link: "https://i.redd.it/h6fid2vmsrfh1.jpeg",
    tags: ["The", "Chinese"],
    created_at: "2026-07-28",
    span: "",
  },
  {
    id: 119,
    slug: "pgsimcity---how-postgresql-works",
    title: "PGSimCity - How PostgreSQL Works",
    summary: "An independent, non-commercial educational visualization of PostgreSQL internals. Not affiliated with Electronic Arts.",
    content: "",
    category: "dev",
    image_url: "/card-news/pgsimcity---how-postgresql-works.png",
    external_link: "https://nikolays.github.io/PGSimCity/",
    tags: ["PGSimCity", "How", "PostgreSQL"],
    created_at: "2026-07-27",
    span: "",
  },
  {
    id: 118,
    slug: "scriptc-by-vercel-typescript-to-native-compiler-no-javascrip",
    title: "Scriptc by Vercel: TypeScript-to-Native compiler, no JavaScript engine in binary",
    summary: "TypeScript-to-Native Compiler. Contribute to vercel-labs/scriptc development by creating an account on GitHub.",
    content: "",
    category: "dev",
    image_url: "/card-news/scriptc-by-vercel-typescript-to-native-compiler-no-javascrip.png",
    external_link: "https://github.com/vercel-labs/scriptc",
    tags: ["Scriptc", "Vercel", "TypeScript"],
    created_at: "2026-07-26",
    span: "",
  },
  {
    id: 117,
    slug: "the-new-rules-of-context-engineering-for-claude-5-generation",
    title: "The new rules of context engineering for Claude 5 generation models",
    summary: "We removed over 80% of Claude Code's system prompt for more advanced models. How to apply the lessons we learned to your own context engineering in Claude Code and with your own agents.",
    content: "",
    category: "ai",
    image_url: "/card-news/the-new-rules-of-context-engineering-for-claude-5-generation.png",
    external_link: "https://claude.com/blog/the-new-rules-of-context-engineering-for-claude-5-generation-models",
    tags: ["The", "Claude"],
    created_at: "2026-07-25",
    span: "",
  },
  {
    id: 116,
    slug: "claude-opus-5",
    title: "Claude Opus 5",
    summary: "Opus 5 is a step change improvement for the Opus tier powering long-running agents while delivering improvements in coding and professional work.",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-opus-5.png",
    external_link: "https://www.anthropic.com/news/claude-opus-5",
    tags: ["Claude", "Opus"],
    created_at: "2026-07-24",
    span: "",
  },
  {
    id: 115,
    slug: "kimi-k3-exploited-the-latest-redis-server",
    title: "Kimi K3 exploited the latest Redis server",
    summary: "Kimi K3 exploited the latest Redis server with a 0day it discovered. All it took was 27min with 32 agents. https://t.co/ZOKA2wchLa",
    content: "",
    category: "ai",
    image_url: "/card-news/kimi-k3-exploited-the-latest-redis-server.png",
    external_link: "https://twitter.com/fried_rice/status/2080059356322918777",
    tags: ["Kimi", "K3", "Redis"],
    created_at: "2026-07-23",
    span: "",
  },
  {
    id: 114,
    slug: "show-hn-bento---an-entire-powerpoint-in-one-html-file-editvi",
    title: "Show HN: Bento - An entire PowerPoint in one HTML file (edit+view+data+collab)",
    summary: "Over the past few months, our team has been building more and more slidedecks using web frontend technologies with coding harnesses like Claude Code, but a common complaint is to make even small edits we need to edit the code either manuall",
    content: "",
    category: "ai",
    image_url: "/card-news/show-hn-bento---an-entire-powerpoint-in-one-html-file-editvi.png",
    external_link: "https://bento.page/slides/",
    tags: ["Show", "HN", "Bento"],
    created_at: "2026-07-22",
    span: "",
  },
  {
    id: 113,
    slug: "gemini-36-flash-35-flash-lite-and-35-flash-cyber",
    title: "Gemini 3.6 Flash, 3.5 Flash-Lite, and 3.5 Flash Cyber",
    summary: "We’re introducing new Gemini models, including Gemini 3.6 Flash, 3.5 Flash-Lite and 3.5 Flash Cyber.",
    content: "",
    category: "ai",
    image_url: "/card-news/gemini-36-flash-35-flash-lite-and-35-flash-cyber.png",
    external_link: "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-6-flash-3-5-flash-lite-3-5-flash-cyber/",
    tags: ["Gemini", "Flash", "Flash"],
    created_at: "2026-07-21",
    span: "",
  },
  {
    id: 112,
    slug: "i-found-a-wordpress-rces-with-gpt56-and-25",
    title: "I found a WordPress RCEs with GPT5.6 and $25",
    summary: "Stay current: Get research alerts for newly disclosed vulnerabilities and exposures If you're running WordPress and want to check if your instance is vulnerable, you can use our tool we've hosted here: https://wp2shell.com/. We held off on ",
    content: "",
    category: "ai",
    image_url: "/card-news/i-found-a-wordpress-rces-with-gpt56-and-25.png",
    external_link: "https://slcyber.io/research-center/exploit-brokers-pay-500000-for-a-wordpress-rce-i-found-one-with-gpt5-6/",
    tags: ["WordPress", "RCEs", "GPT5.6"],
    created_at: "2026-07-20",
    span: "",
  },
  {
    id: 111,
    slug: "show-hn-i-replaced-a-120k-bowling-center-system-with-1600-in",
    title: "Show HN: I replaced a $120k bowling center system with $1,600 in ESP32s",
    summary: "I might be the only SRE on Earth with his own bowling center. It&#x27;s a more in-depth gig than you&#x27;d think. My family and I bought an abandoned 8-lane bowling center in the rural mid-west. In our small town there weren&#x27;t many re",
    content: "",
    category: "news",
    image_url: "/card-news/show-hn-i-replaced-a-120k-bowling-center-system-with-1600-in.png",
    external_link: "https://news.ycombinator.com/item?id=48968606",
    tags: ["Show", "HN", "ESP32s"],
    created_at: "2026-07-19",
    span: "",
  },
  {
    id: 110,
    slug: "gpt-56-used-a-prompt-to-close-a-30-year-gap-in-convex-optimi",
    title: "GPT-5.6 used a prompt to close a 30-year gap in convex optimization",
    summary: "TL;DR: In a single 148 min session, with a prompt modeled after the one OpenAI used to prove CDC, GPT 5.6 Sol Pro supplied a proof that closed a...",
    content: "",
    category: "ai",
    image_url: "/card-news/gpt-56-used-a-prompt-to-close-a-30-year-gap-in-convex-optimi.png",
    external_link: "https://old.reddit.com/r/math/comments/1uxj3cy/after_openais_cdc_proof_announcement_gpt56_used_a/",
    tags: ["GPT"],
    created_at: "2026-07-18",
    span: "",
  },
  {
    id: 109,
    slug: "kimi-k3-and-what-we-can-still-learn-from-the-pelican-benchma",
    title: "Kimi K3, and what we can still learn from the pelican benchmark",
    summary: "Chinese AI lab Moonshot AI announced Kimi K3 this morning, describing it as their “most capable model to date, with 2.8 trillion parameters”. It’s currently available via their website and …",
    content: "",
    category: "ai",
    image_url: "/card-news/kimi-k3-and-what-we-can-still-learn-from-the-pelican-benchma.png",
    external_link: "https://simonwillison.net/2026/Jul/16/kimi-k3/",
    tags: ["Kimi", "K3"],
    created_at: "2026-07-17",
    span: "",
  },
  {
    id: 108,
    slug: "kimi-k3-open-frontier-intelligence",
    title: "Kimi K3: Open Frontier Intelligence",
    summary: "Kimi K3 is the world's first open 3T-class model — frontier performance across coding, knowledge work, and reasoning, with native multimodality and 1M context.",
    content: "",
    category: "ai",
    image_url: "/card-news/kimi-k3-open-frontier-intelligence.png",
    external_link: "https://www.kimi.com/blog/kimi-k3",
    tags: ["Kimi", "K3", "Open"],
    created_at: "2026-07-16",
    span: "",
  },
  {
    id: 107,
    slug: "show-hn-firefox-in-webassembly",
    title: "Show HN: Firefox in WebAssembly",
    summary: "This is the entire Firefox browser rendering to a &lt;canvas&gt; element. Gecko, all UI components, and the Spidermonkey JS engine are all compiled and running in WebAssembly. Here are a few things you might find interesting: - This is full",
    content: "",
    category: "dev",
    image_url: "/card-news/show-hn-firefox-in-webassembly.png",
    external_link: "https://developer.puter.com/labs/firefox-wasm/",
    tags: ["Show", "HN", "Firefox"],
    created_at: "2026-07-15",
    span: "",
  },
  {
    id: 106,
    slug: "bonsai-27b-a-27b-class-model-that-runs-on-a-phone",
    title: "Bonsai 27B: A 27B-Class model that runs on a phone",
    summary: "27B급 성능을 유지하면서 스마트폰에서 구동 가능하도록 설계된 모델. 온디바이스 추론을 목표로 메모리 사용량과 연산량을 대폭 줄였다.",
    content: "",
    category: "ai",
    image_url: "/card-news/bonsai-27b-a-27b-class-model-that-runs-on-a-phone.png",
    external_link: "https://prismml.com/news/bonsai-27b",
    tags: ["Bonsai", "Class"],
    created_at: "2026-07-14",
    span: "",
  },
  {
    id: 105,
    slug: "apples-new-speechanalyzer-api-benchmarked-against-whisper-an",
    title: "Apple's new SpeechAnalyzer API, benchmarked against Whisper and its predecessor",
    summary: "SpeechAnalyzer vs SFSpeechRecognizer vs Whisper on 5,559 LibriSpeech utterances. Apple never published accuracy numbers. Here they are, with raw transcripts you can rescore.",
    content: "",
    category: "dev",
    image_url: "/card-news/apples-new-speechanalyzer-api-benchmarked-against-whisper-an.png",
    external_link: "https://get-inscribe.com/blog/apple-speech-api-benchmark.html",
    tags: ["Apple", "SpeechAnalyzer", "API"],
    created_at: "2026-07-13",
    span: "",
  },
  {
    id: 104,
    slug: "claude-code-sends-33k-tokens-before-reading-the-prompt-openc",
    title: "Claude Code sends 33k tokens before reading the prompt; OpenCode sends 7k",
    summary: "Claude Code vs OpenCode token overhead measured at the API boundary. Out-of-the-box baselines, instruction file weight, MCP schema tax, subagent multipliers, and cache-write behaviour.",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-code-sends-33k-tokens-before-reading-the-prompt-openc.png",
    external_link: "https://systima.ai/blog/claude-code-vs-opencode-token-overhead",
    tags: ["Claude", "Code", "OpenCode"],
    created_at: "2026-07-12",
    span: "",
  },
  {
    id: 103,
    slug: "show-hn-ant-a-javascript-runtime-and-ecosystem",
    title: "Show HN: Ant – A JavaScript runtime and ecosystem",
    summary: "Run real npm packages and TypeScript - all from a single 9 MB binary. Ant is a lightweight JavaScript runtime built from scratch on its own engine, with a Node-compatible API, a VM-isolated sandbox, and Wasm support built-in.",
    content: "",
    category: "dev",
    image_url: "/card-news/show-hn-ant-a-javascript-runtime-and-ecosystem.png",
    external_link: "https://antjs.org",
    tags: ["Show", "HN", "Ant"],
    created_at: "2026-07-11",
    span: "",
  },
  {
    id: 102,
    slug: "gpt-56-sol-ultra-produces-proof-of-the-cycle-double-cover-co",
    title: "GPT-5.6 Sol Ultra produces proof of the Cycle Double Cover Conjecture [pdf]",
    summary: "https:&#x2F;&#x2F;x.com&#x2F;__eknight__&#x2F;status&#x2F;2075643450196971805 ,  https:&#x2F;&#x2F;xcancel.com&#x2F;__eknight__&#x2F;status&#x2F;2075643450196971805  Prompt:  https:&#x2F;&#x2F;cdn.openai.com&#x2F;pdf&#x2F;04d1d1e4-bc75-476a",
    content: "",
    category: "ai",
    image_url: "/card-news/gpt-56-sol-ultra-produces-proof-of-the-cycle-double-cover-co.png",
    external_link: "https://cdn.openai.com/pdf/04d1d1e4-bc75-476a-97cf-49055cd98d31/cdc_proof.pdf",
    tags: ["GPT", "Sol", "Ultra"],
    created_at: "2026-07-10",
    span: "",
  },
  {
    id: 101,
    slug: "gpt-56",
    title: "GPT-5.6",
    summary: "More intelligence from every token, stronger performance per dollar, and more capability on demand for your hardest work.",
    content: "",
    category: "ai",
    image_url: "/card-news/gpt-56.png",
    external_link: "https://openai.com/index/gpt-5-6/",
    tags: ["GPT"],
    created_at: "2026-07-09",
    span: "",
  },
  {
    id: 100,
    slug: "gitlost-we-tricked-githubs-ai-agent-into-leaking-private-rep",
    title: "GitLost: We Tricked GitHub's AI Agent into Leaking Private Repos",
    summary: "GitLost: We Tricked GitHub's AI Agent into Leaking Private Repos",
    content: "",
    category: "ai",
    image_url: "/card-news/gitlost-we-tricked-githubs-ai-agent-into-leaking-private-rep.png",
    external_link: "https://noma.security/blog/gitlost-how-we-tricked-githubs-ai-agent-into-leaking-private-repos/",
    tags: ["GitLost", "We", "Tricked"],
    created_at: "2026-07-08",
    span: "",
  },
  {
    id: 99,
    slug: "show-hn-rowboat-open-source-local-first-alternative-to-claud",
    title: "Show HN: Rowboat – Open-source, local-first alternative to Claude Desktop",
    summary: "Open-source AI coworker, with memory. Contribute to rowboatlabs/rowboat development by creating an account on GitHub.",
    content: "",
    category: "ai",
    image_url: "/card-news/show-hn-rowboat-open-source-local-first-alternative-to-claud.png",
    external_link: "https://github.com/rowboatlabs/rowboat",
    tags: ["Show", "HN", "Rowboat"],
    created_at: "2026-07-07",
    span: "",
  },
  {
    id: 98,
    slug: "openwrt-one-open-hardware-router",
    title: "OpenWrt One – Open Hardware Router",
    summary: "OpenWrt One – Open Hardware Router",
    content: "",
    category: "news",
    image_url: "/card-news/openwrt-one-open-hardware-router.png",
    external_link: "https://openwrt.org/toh/openwrt/one",
    tags: ["OpenWrt", "One", "Open"],
    created_at: "2026-07-06",
    span: "",
  },
  {
    id: 97,
    slug: "show-hn-kicad-in-the-browser",
    title: "Show HN: KiCad in the Browser",
    summary: "Early-access alpha of PCBJam — KiCad running in your browser. Open the example boards or your own KiCad project. No install, nothing uploaded.",
    content: "",
    category: "dev",
    image_url: "/card-news/show-hn-kicad-in-the-browser.png",
    external_link: "https://demo.pcbjam.com/",
    tags: ["Show", "HN", "KiCad"],
    created_at: "2026-07-05",
    span: "",
  },
  {
    id: 96,
    slug: "zig-all-package-management-functionality-moved-from-compiler",
    title: "Zig: All Package Management Functionality Moved from Compiler to Build System",
    summary: "Zig: All Package Management Functionality Moved from Compiler to Build System",
    content: "",
    category: "dev",
    image_url: "/card-news/zig-all-package-management-functionality-moved-from-compiler.png",
    external_link: "https://ziglang.org/devlog/2026/#2026-06-30",
    tags: ["Zig", "All", "Package"],
    created_at: "2026-07-04",
    span: "",
  },
  {
    id: 95,
    slug: "jamesobs-guide-to-running-sota-llms-locally",
    title: "Jamesob's guide to running SOTA LLMs locally",
    summary: "Everything I know about running LLMs locally. Contribute to jamesob/local-llm development by creating an account on GitHub.",
    content: "",
    category: "ai",
    image_url: "/card-news/jamesobs-guide-to-running-sota-llms-locally.png",
    external_link: "https://github.com/jamesob/local-llm",
    tags: ["Jamesob", "SOTA", "LLMs"],
    created_at: "2026-07-03",
    span: "",
  },
  {
    id: 94,
    slug: "kimi-k27-code-is-generally-available-in-github-copilot",
    title: "Kimi K2.7 Code is generally available in GitHub Copilot",
    summary: "Kimi K2.7 Code, an open-weight model, is now generally available in GitHub Copilot. This is the first open-weight model offered as a selectable option in the Copilot model picker, giving…",
    content: "",
    category: "ai",
    image_url: "/card-news/kimi-k27-code-is-generally-available-in-github-copilot.png",
    external_link: "https://github.blog/changelog/2026-07-01-kimi-k2-7-is-now-available-in-github-copilot/",
    tags: ["Kimi", "K2.7", "Code"],
    created_at: "2026-07-02",
    span: "",
  },
  {
    id: 57,
    slug: "누군가는-토스를-테스트하는-동안-우리는-테스트하는-법을-만듭니다",
    title: "누군가는 토스를 테스트하는 동안, 우리는 테스트하는 법을 만듭니다.",
    summary: "빠른 변화가 품질과 함께 흐르도록",
    content: "",
    category: "news",
    image_url: "/card-news/누군가는-토스를-테스트하는-동안-우리는-테스트하는-법을-만듭니다.png",
    external_link: "https://toss.tech/article/50893",
    tags: ["AI", "기술", "트렌드"],
    created_at: "2026-07-01",
    span: "",
  },
  {
    id: 58,
    slug: "ai-에이전트-회사-차리기-설립부터-어디서든-동기화까지",
    title: "AI 에이전트 회사 차리기: 설립부터 어디서든 동기화까지",
    summary: "네이버 사내 기술 교류 행사인 NAVER ENGINEERING DAY 2026(5월)에서 발표되었던 세션을 공개합니다. 발표 내용 AI 에이전트로 나만의 회사를 차리고, 어디서 접속하든 같은 구성원이 같은 목표로 일하게 만든 이야기입니다. 발표 대상 AI 에이전트 활용에 관심있는 분들 목차 PROLOGUE — Claude Code, 매일 쓰는데 왜 매번 처음인가요? PLATFORM — NaverMadCat이란 ORGANIZAT",
    content: "",
    category: "news",
    image_url: "/card-news/ai-에이전트-회사-차리기-설립부터-어디서든-동기화까지.png",
    external_link: "https://d2.naver.com/helloworld/3897377",
    tags: ["AI"],
    created_at: "2026-06-30",
    span: "",
  },
  {
    id: 59,
    slug: "end-to-end-유저-모니터링-rum-으로-한방에-해결",
    title: "End to End 유저 모니터링 RUM 으로 한방에 해결!!",
    summary: "네이버 사내 기술 교류 행사인 NAVER ENGINEERING DAY 2026(5월)에서 발표되었던 세션을 공개합니다. 발표 내용 End To End 모니터링을 별도의 작업없이 제공 받을수 있는 nFront RUM 서비스를 소개합니다. 내부 솔루션만으로 구현한 서비스로 별도의 비용 없이 AI report까지 제공되는 Real User Monitoring 서비스 입니다. 발표 대상 서비스 품질 측정과 모니터링 작업에 관심있는 개",
    content: "",
    category: "news",
    image_url: "/card-news/end-to-end-유저-모니터링-rum-으로-한방에-해결.png",
    external_link: "https://d2.naver.com/helloworld/9227131",
    tags: ["End", "End", "RUM"],
    created_at: "2026-06-29",
    span: "",
  },
  {
    id: 60,
    slug: "한-번-성공하니-다음도-쉬울-줄-알았다-최소주문금액바-4번의-ab실험",
    title: "한 번 성공하니 다음도 쉬울 줄 알았다: 최소주문금액바 4번의 A/B실험",
    summary: "들어가며 2024년 10월, 배달의민족 장보기·쇼핑 서비스에 ‘최소주문금액바’라는 스낵바 형태의 UI를 도입했습니다. 퀵커머스는 빠른 배달이 강점이지만, 그만큼 배달 비용도 높습니다. 라이더가 한 번에 배달할 수 있는 주문 수가 제한적이기 때문입니다. 그래서 퀵커머스 서비스에는 일정 금액 이상 주문해야 하는 ‘최소주문금액’이 존재합니다. 최소주문금액바는 고객이 이 기준까지 얼마나 남았는지를 쉽게 알 수 있도록 만든 기능이었어요",
    content: "",
    category: "news",
    image_url: "/card-news/한-번-성공하니-다음도-쉬울-줄-알았다-최소주문금액바-4번의-ab실험.png",
    external_link: "https://techblog.woowahan.com/26379/",
    tags: ["AI", "기술", "트렌드"],
    created_at: "2026-06-28",
    span: "",
  },
  {
    id: 61,
    slug: "ai로-웹-엔지니어-없이-line-앱-안에서-그룹-영상-통화-서비스-만들기",
    title: "AI로 웹 엔지니어 없이 LINE 앱 안에서 그룹 영상 통화 서비스 만들기",
    summary: "들어가며LINE Developers를 통해 이용할 수 있는 LIFF(LINE Front-end Framework)를 활용하면, LINE 앱 사용자를 대상으로 나만의 서비스 공간을 ...",
    content: "",
    category: "news",
    image_url: "/card-news/ai로-웹-엔지니어-없이-line-앱-안에서-그룹-영상-통화-서비스-만들기.png",
    external_link: "https://techblog.lycorp.co.jp/ko/building-group-video-calls-inside-line-app-with-ai-and-line-planet",
    tags: ["AI", "LINE"],
    created_at: "2026-06-27",
    span: "",
  },
  {
    id: 62,
    slug: "프롬프팅에서-워크플로로-ai로-프런트엔드-개발-생산성-끌어올리기",
    title: "프롬프팅에서 워크플로로, AI로 프런트엔드 개발 생산성 끌어올리기",
    summary: "LY Corporation의 기술 컨퍼런스인 Tech-Verse 2026의 공식 기사입니다.AI 생성 이미지코딩 속도는 더 이상 가장 큰 병목이 아닙니다. 이제 병목은 입력이 여러...",
    content: "",
    category: "news",
    image_url: "/card-news/프롬프팅에서-워크플로로-ai로-프런트엔드-개발-생산성-끌어올리기.png",
    external_link: "https://techblog.lycorp.co.jp/ko/techverse2026-10",
    tags: ["AI"],
    created_at: "2026-06-26",
    span: "",
  },
  {
    id: 63,
    slug: "임베딩-안정화로-검색-리랭킹의-콜드-스타트-문제를-해결하다-line-part-time-jobs-적용-사례",
    title: "임베딩 안정화로 검색 리랭킹의 콜드 스타트 문제를 해결하다: LINE Part Time Jobs 적용 사례",
    summary: "LY Corporation의 기술 컨퍼런스인 Tech-Verse 2026의 공식 기사입니다.안녕하세요. LY Corporation에서 머신러닝 플랫폼을 개발하고 있는 Kenta K...",
    content: "",
    category: "news",
    image_url: "/card-news/임베딩-안정화로-검색-리랭킹의-콜드-스타트-문제를-해결하다-line-part-time-jobs-적용-사례.png",
    external_link: "https://techblog.lycorp.co.jp/ko/techverse2026-62",
    tags: ["LINE", "Part", "Time"],
    created_at: "2026-06-25",
    span: "",
  },
  {
    id: 64,
    slug: "혼자-시작해-전국-오픈까지-당근-레슨과외-빌딩-로그",
    title: "혼자 시작해 전국 오픈까지, 당근 레슨/과외 빌딩 로그",
    summary: "안녕하세요. 당근 Lessons &amp; Tutoring 팀에서 레슨/과외 프로덕트를 만들고 있는 Bucky예요.대부분의 사람들은 여전히 “당근 = 중고거래”라는 인식이 강하지만, 그 안에는 여러 숨겨진 기회가 있어요. 이번 글에서는 이미 형성된 마켓플레이스, 당근에서 레슨/과외 서비스를 빌딩하며 느낀 점을 공유해 보려고 해요.아직 레슨/과외 서비스가 낯선 분도 계실 텐데요. 위 이미지처럼 당근 레슨/과외는 동네에서 뭔가 배",
    content: "",
    category: "news",
    image_url: "/card-news/혼자-시작해-전국-오픈까지-당근-레슨과외-빌딩-로그.png",
    external_link: "https://medium.com/daangn/%ED%98%BC%EC%9E%90-%EC%8B%9C%EC%9E%91%ED%95%B4-%EC%A0%84%EA%B5%AD-%EC%98%A4%ED%94%88%EA%B9%8C%EC%A7%80-%EB%8B%B9%EA%B7%BC-%EB%A0%88%EC%8A%A8-%EA%B3%BC%EC%99%B8-%EB%B9%8C%EB%94%A9-%EB%A1%9C%EA%B7%B8-d4e61f6ba32f?source=rss----4505f82a2dbd---4",
    tags: ["AI", "기술", "트렌드"],
    created_at: "2026-06-24",
    span: "",
  },
  {
    id: 65,
    slug: "jvm-heap은-멀쩡한데-왜-메모리가-터질까-docker-환경-네이티브-메모리-삽질기-part-2",
    title: "JVM heap은 멀쩡한데 왜 메모리가 터질까? — Docker 환경 네이티브 메모리 삽질기 (Part 2)",
    summary: "글. 박성진(Philip) / 전시개발팀안녕하세요, 지난 편에 이어 네이티브 메모리 이야기를 마저 풀어보려고 합니다.1편에서는 이런 상태에서 멈췄었죠.JVM 메모리 = 힙 + 네이티브 메모리NMT로 네이티브 메모리를 추적할 수 있지만, 한계가 있다. JVM 밖에서 일어난 malloc은 못 봅니다.NMT 기준 9GB vs 실제 RSS 14GB, 약 5GB가 행방불명그리고 세 가지 질문을 남겨뒀습니다.그 5GB는 어디서 쓰고 있나",
    content: "",
    category: "news",
    image_url: "/card-news/jvm-heap은-멀쩡한데-왜-메모리가-터질까-docker-환경-네이티브-메모리-삽질기-part-2.png",
    external_link: "https://techblog.gccompany.co.kr/jvm-heap%EC%9D%80-%EB%A9%80%EC%A9%A1%ED%95%9C%EB%8D%B0-%EC%99%9C-%EB%A9%94%EB%AA%A8%EB%A6%AC%EA%B0%80-%ED%84%B0%EC%A7%88%EA%B9%8C-docker-%ED%99%98%EA%B2%BD-%EB%84%A4%EC%9D%B4%ED%8B%B0%EB%B8%8C-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%82%BD%EC%A7%88%EA%B8%B0-part-2-c4d782935a79?source=rss----18356045d353---4",
    tags: ["JVM", "Docker", "Part"],
    created_at: "2026-06-23",
    span: "",
  },
  {
    id: 66,
    slug: "jvm-heap은-멀쩡한데-왜-메모리가-터질까-docker-환경-네이티브-메모리-삽질기-part-1",
    title: "JVM heap은 멀쩡한데 왜 메모리가 터질까? — Docker 환경 네이티브 메모리 삽질기 (Part 1)",
    summary: "JVM heap은 멀쩡한데 왜 메모리가 터질까? — Docker 환경 네이티브 메모리 삽질기 (Part 1)글. 박성진(Philip) / 전시개발팀안녕하세요 여기어때 전시 개발팀 백엔드 개발자 필립입니다.오늘은 제가 2년 전 겪었던 꽤나 골치 아팠던 메모리 이슈에 대해 이야기해보려고 합니다. 같은 문제로 고민하시는 분들께 도움이 되었으면 좋겠습니다.들어가며2년전 어느 날 모니터링 알람이 울렸습니다. 서버 메모리 사용량이 80%",
    content: "",
    category: "news",
    image_url: "/card-news/jvm-heap은-멀쩡한데-왜-메모리가-터질까-docker-환경-네이티브-메모리-삽질기-part-1.png",
    external_link: "https://techblog.gccompany.co.kr/jvm-heap%EC%9D%80-%EB%A9%80%EC%A9%A1%ED%95%9C%EB%8D%B0-%EC%99%9C-%EB%A9%94%EB%AA%A8%EB%A6%AC%EA%B0%80-%ED%84%B0%EC%A7%88%EA%B9%8C-docker-%ED%99%98%EA%B2%BD-%EB%84%A4%EC%9D%B4%ED%8B%B0%EB%B8%8C-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%82%BD%EC%A7%88%EA%B8%B0-part-1-4d48d788e1cc?source=rss----18356045d353---4",
    tags: ["JVM", "Docker", "Part"],
    created_at: "2026-06-22",
    span: "",
  },
  {
    id: 67,
    slug: "spring-data-redis-repository-vs-redistemplate-실전-성능-비교",
    title: "Spring Data Redis: Repository vs RedisTemplate — 실전 성능 비교",
    summary: "Spring Data Redis: Repository vs RedisTemplate — 실전 성능 비교글. 박성진(Philip) / 전시개발팀들어가며: Redis Repository 프로덕션 장애에서 배운 교훈안녕하세요 여기어때 전시 개발 팀에서 백엔드를 담당하고 있는 필립입니다.전시 개발 팀에서는 Redis를 운영하는 과정에서 두 번의 심각한 장애를 겪었습니다. 이번 시리즈에서는 그 중 하나인 Redis CPU 100% 이슈",
    content: "",
    category: "news",
    image_url: "/card-news/spring-data-redis-repository-vs-redistemplate-실전-성능-비교.png",
    external_link: "https://techblog.gccompany.co.kr/spring-data-redis-repository-vs-redistemplate-%EC%8B%A4%EC%A0%84-%EC%84%B1%EB%8A%A5-%EB%B9%84%EA%B5%90-3e1a6ab8bda3?source=rss----18356045d353---4",
    tags: ["Spring", "Data", "Redis"],
    created_at: "2026-06-21",
    span: "",
  },
  {
    id: 93,
    slug: "linux-eliminates-the-strncpy-api-after-six-years-of-work-360",
    title: "Linux eliminates the strncpy API after six years of work, 360 patches",
    summary: "Linux 7.2 has finally eliminated the strncpy API from the Linux kernel",
    content: "",
    category: "dev",
    image_url: "/card-news/linux-eliminates-the-strncpy-api-after-six-years-of-work-360.png",
    external_link: "https://www.phoronix.com/news/Linux-7.2-Drops-strncpy",
    tags: ["Linux", "API"],
    created_at: "2026-06-20",
    span: "",
  },
  {
    id: 92,
    slug: "project-valhalla-explained-how-a-decade-of-work-arrives-in-j",
    title: "Project Valhalla, Explained: How a Decade of Work Arrives in JDK 28",
    summary: "The new JVM Weekly is here... and Ragnarok seems to come, as we finally have Valhalla in the JDK. However, situation is a bit... nuanced.",
    content: "",
    category: "dev",
    image_url: "/card-news/project-valhalla-explained-how-a-decade-of-work-arrives-in-j.png",
    external_link: "https://www.jvm-weekly.com/p/project-valhalla-explained-how-a",
    tags: ["Project", "Valhalla", "Explained"],
    created_at: "2026-06-19",
    span: "",
  },
  {
    id: 91,
    slug: "i-found-10k-github-repositories-distributing-trojan-malware",
    title: "I found 10k GitHub repositories distributing Trojan malware",
    summary: "This is the story of how I found 10,000 repositories on GitHub that distribute Trojan malware. They are all from different contributors, have different names, and are not forks of other repositories. But they share a common pattern, which i",
    content: "",
    category: "dev",
    image_url: "/card-news/i-found-10k-github-repositories-distributing-trojan-malware.png",
    external_link: "https://orchidfiles.com/github-repositories-distributing-malware/",
    tags: ["GitHub", "Trojan"],
    created_at: "2026-06-18",
    span: "",
  },
  {
    id: 90,
    slug: "lore-open-source-version-control-system-designed-for-scalabi",
    title: "Lore – Open source version control system designed for scalability",
    summary: "Maintained by Epic Games, Lore is designed for unprecedented scalability of both data and teams. It’s optimized for projects that combine code with large binary assets.",
    content: "",
    category: "dev",
    image_url: "/card-news/lore-open-source-version-control-system-designed-for-scalabi.png",
    external_link: "https://lore.org/",
    tags: ["Lore", "Open"],
    created_at: "2026-06-17",
    span: "",
  },
  {
    id: 89,
    slug: "running-local-models-is-good-now",
    title: "Running local models is good now",
    summary: "Local agentic coding has gotten great over the past few months",
    content: "",
    category: "ai",
    image_url: "/card-news/running-local-models-is-good-now.png",
    external_link: "https://vickiboykis.com/2026/06/15/running-local-models-is-good-now/",
    tags: ["Running"],
    created_at: "2026-06-16",
    span: "",
  },
  {
    id: 88,
    slug: "iroh-10",
    title: "Iroh 1.0",
    summary: "Iroh 1.0 is out. Now is the time to build.",
    content: "",
    category: "news",
    image_url: "/card-news/iroh-10.png",
    external_link: "https://www.iroh.computer/blog/v1",
    tags: ["Iroh"],
    created_at: "2026-06-15",
    span: "",
  },
  {
    id: 87,
    slug: "show-hn-kage-shadow-any-website-to-a-single-binary-for-offli",
    title: "Show HN: Kage – Shadow any website to a single binary for offline viewing",
    summary: "Shadow any website for offline viewing, with the JavaScript stripped out - tamnd/kage",
    content: "",
    category: "dev",
    image_url: "/card-news/show-hn-kage-shadow-any-website-to-a-single-binary-for-offli.png",
    external_link: "https://github.com/tamnd/kage",
    tags: ["Show", "HN", "Kage"],
    created_at: "2026-06-14",
    span: "",
  },
  {
    id: 86,
    slug: "statement-on-us-government-directive-to-suspend-access-to-fa",
    title: "Statement on US government directive to suspend access to Fable 5 and Mythos 5",
    summary: "The US government has issued an export control directive to suspend all access to Fable 5 and Mythos 5 by any foreign national, whether inside or outside the United States.",
    content: "",
    category: "news",
    image_url: "/card-news/statement-on-us-government-directive-to-suspend-access-to-fa.png",
    external_link: "https://www.anthropic.com/news/fable-mythos-access",
    tags: ["Statement", "US", "Fable"],
    created_at: "2026-06-13",
    span: "",
  },
  {
    id: 85,
    slug: "kimi-k27-code-open-source-coding-model-with-better-token-eff",
    title: "Kimi K2.7-Code: open-source coding model with better token efficiency",
    summary: "We’re on a journey to advance and democratize artificial intelligence through open source and open science.",
    content: "",
    category: "ai",
    image_url: "/card-news/kimi-k27-code-open-source-coding-model-with-better-token-eff.png",
    external_link: "https://huggingface.co/moonshotai/Kimi-K2.7-Code",
    tags: ["Kimi", "K2.7", "Code"],
    created_at: "2026-06-12",
    span: "",
  },
  {
    id: 84,
    slug: "show-hn-homebrew-600",
    title: "Show HN: Homebrew 6.0.0",
    summary: "Today, I’m proud to announce Homebrew 6.0.0. The most significant changes since 5.1.0 are a new tap trust security mechanism, the new faster, smaller, default internal Homebrew JSON API, sandboxing on Linux, better defaults informed by our ",
    content: "",
    category: "dev",
    image_url: "/card-news/show-hn-homebrew-600.png",
    external_link: "https://brew.sh/2026/06/11/homebrew-6.0.0/",
    tags: ["Show", "HN", "Homebrew"],
    created_at: "2026-06-11",
    span: "",
  },
  {
    id: 83,
    slug: "building-an-html-first-site-doubled-our-users-overnight",
    title: "Building an HTML-first site doubled our users overnight",
    summary: "My client was a utility company, and they had a big problem...",
    content: "",
    category: "news",
    image_url: "/card-news/building-an-html-first-site-doubled-our-users-overnight.png",
    external_link: "https://mohkohn.co.uk/writing/html-first/",
    tags: ["Building", "HTML"],
    created_at: "2026-06-10",
    span: "",
  },
  {
    id: 82,
    slug: "claude-fable-5",
    title: "Claude Fable 5",
    summary: "Today we’re launching Claude Fable 5: a Mythos-class model that we’ve made safe for general use.",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-fable-5.png",
    external_link: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
    tags: ["Claude", "Fable"],
    created_at: "2026-06-09",
    span: "",
  },
  {
    id: 81,
    slug: "apple-reveals-new-ai-architecture-built-around-google-gemini",
    title: "Apple reveals new AI architecture built around Google Gemini models",
    summary: "Apple today announced a major overhaul of its Apple Intelligence platform, revealing a new architecture built on foundation models developed in collaboration with Google using the technologies behind the Gemini family. The new architecture ",
    content: "",
    category: "ai",
    image_url: "/card-news/apple-reveals-new-ai-architecture-built-around-google-gemini.png",
    external_link: "https://www.macrumors.com/2026/06/08/apple-reveals-new-ai-architecture/",
    tags: ["Apple", "AI", "Google"],
    created_at: "2026-06-08",
    span: "",
  },
  {
    id: 80,
    slug: "show-hn-lathe-use-llms-to-learn-a-new-domain-not-skip-past-i",
    title: "Show HN: Lathe – Use LLMs to learn a new domain, not skip past it",
    summary: "Generate hands-on, multi-part technical tutorials on demand, with LLM skills tuned to make content approachable. Then you work through them yourself, by hand ✋ - devenjarvis/lathe",
    content: "",
    category: "ai",
    image_url: "/card-news/show-hn-lathe-use-llms-to-learn-a-new-domain-not-skip-past-i.png",
    external_link: "https://github.com/devenjarvis/lathe",
    tags: ["Show", "HN", "Lathe"],
    created_at: "2026-06-07",
    span: "",
  },
  {
    id: 79,
    slug: "opencv-5-is-here-the-biggest-leap-in-years-for-computer-visi",
    title: "OpenCV 5 Is Here: The Biggest Leap in Years for Computer Vision",
    summary: "OpenCV 5 is here! A massive modernization brings a graph-based DNN engine, over 80% ONNX coverage, hardware acceleration, LLM/VLM support, and a faster Python-first core. Learn why this isn't just an incremental update.",
    content: "",
    category: "ai",
    image_url: "/card-news/opencv-5-is-here-the-biggest-leap-in-years-for-computer-visi.png",
    external_link: "https://opencv.org/opencv-5/",
    tags: ["OpenCV", "Is", "Here"],
    created_at: "2026-06-06",
    span: "",
  },
  {
    id: 56,
    slug: "토스팀이-ai-파도를-마주하는-방법-ai-surf-day",
    title: "토스팀이 AI 파도를 마주하는 방법: AI Surf Day",
    summary: "파도를 멈출 수는 없지만, 서핑하는 방법은 배울 수 있다.",
    content: "",
    category: "news",
    image_url: "/card-news/토스팀이-ai-파도를-마주하는-방법-ai-surf-day.png",
    external_link: "https://toss.tech/article/ai-surf-day",
    tags: ["AI", "AI", "Surf"],
    created_at: "2026-06-05",
    span: "",
  },
  {
    id: 78,
    slug: "anthropics-open-source-framework-for-ai-powered-vulnerabilit",
    title: "Anthropic's open-source framework for AI-powered vulnerability discovery",
    summary: "Skills for threat modeling, scanning, triage, patching, plus an autonomous scanning harness you can /customize - anthropics/defending-code-reference-harness",
    content: "",
    category: "ai",
    image_url: "/card-news/anthropics-open-source-framework-for-ai-powered-vulnerabilit.png",
    external_link: "https://github.com/anthropics/defending-code-reference-harness",
    tags: ["Anthropic", "AI"],
    created_at: "2026-06-04",
    span: "",
  },
  {
    id: 77,
    slug: "elixir-v120-now-a-gradually-typed-language",
    title: "Elixir v1.20: Now a gradually typed language",
    summary: "From Elixir v1.20, every program is now gradually type checked in search for verified bugs and typing violations.",
    content: "",
    category: "dev",
    image_url: "/card-news/elixir-v120-now-a-gradually-typed-language.png",
    external_link: "https://elixir-lang.org/blog/2026/06/03/elixir-v1-20-0-released/",
    tags: ["Elixir", "Now"],
    created_at: "2026-06-03",
    span: "",
  },
  {
    id: 76,
    slug: "plutojl-10-release-reactive-notebook-for-julia",
    title: "Pluto.jl 1.0 release – reactive notebook for Julia",
    summary: "After six years, it’s time to release Pluto version 1.0! With this release, I want to celebrate all the progress over the past years, and to symbolise that Pluto is ready. I am proud of what we have achieved, and I hope you enjoy it! This i",
    content: "",
    category: "dev",
    image_url: "/card-news/plutojl-10-release-reactive-notebook-for-julia.png",
    external_link: "https://discourse.julialang.org/t/pluto-1-0-release/137296",
    tags: ["Pluto.jl", "Julia"],
    created_at: "2026-06-02",
    span: "",
  },
  {
    id: 75,
    slug: "openai-frontier-models-and-codex-are-now-available-on-aws",
    title: "OpenAI frontier models and Codex are now available on AWS",
    summary: "OpenAI frontier models and Codex are now generally available on AWS, giving enterprises a new path to build with OpenAI through the AWS environments, controls, and procurement workflows they already use. Customers can get started with OpenA",
    content: "",
    category: "ai",
    image_url: "/card-news/openai-frontier-models-and-codex-are-now-available-on-aws.png",
    external_link: "https://openai.com/index/openai-frontier-models-and-codex-are-now-available-on-aws/",
    tags: ["OpenAI", "Codex", "AWS"],
    created_at: "2026-06-01",
    span: "",
  },
  {
    id: 74,
    slug: "claude-code-and-codex-can-have-real-time-conversation-via-gi",
    title: "Claude Code and Codex can have real-time conversation via Git",
    summary: "While Claude Code and Codex have significantly accelerated the automation of software development, limitations in the context window of a…",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-code-and-codex-can-have-real-time-conversation-via-gi.png",
    external_link: "https://medium.com/@Koukyosyumei/claude-code-and-codex-can-have-real-time-conversation-via-git-f95b696c1c05",
    tags: ["Claude", "Code", "Codex"],
    created_at: "2026-05-31",
    span: "",
  },
  {
    id: 73,
    slug: "the-av2-video-standard-has-released-final-v10-specification",
    title: "The AV2 Video Standard Has Released (Final v1.0 Specification)",
    summary: "The AV2 Video Standard Has Released (Final v1.0 Specification)",
    content: "",
    category: "news",
    image_url: "/card-news/the-av2-video-standard-has-released-final-v10-specification.png",
    external_link: "https://av2.aomedia.org",
    tags: ["The", "AV2", "Video"],
    created_at: "2026-05-30",
    span: "",
  },
  {
    id: 72,
    slug: "claude-code-everything-you-can-configure-that-the-docs-dont-",
    title: "Claude Code – Everything you can configure that the docs don't tell you",
    summary: "Hook fields that rewrite commands mid-flight, persistent agent memory, auto-mode rules in plain English, self-improving dream loops, and every example is copy-paste ready.",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-code-everything-you-can-configure-that-the-docs-dont-.png",
    external_link: "https://buildingbetter.tech/p/i-read-the-claude-code-source-code",
    tags: ["Claude", "Code", "Everything"],
    created_at: "2026-05-29",
    span: "",
  },
  {
    id: 71,
    slug: "claude-opus-48",
    title: "Claude Opus 4.8",
    summary: "Our latest model, Claude Opus 4.8, is an upgrade to our Opus class of models, with stronger performance across coding, agentic tasks, and professional work, and the consistency to handle long-running work.",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-opus-48.png",
    external_link: "https://www.anthropic.com/news/claude-opus-4-8",
    tags: ["Claude", "Opus"],
    created_at: "2026-05-28",
    span: "",
  },
  {
    id: 70,
    slug: "show-hn-posthorn-self-hosted-mail-gateway",
    title: "Show HN: Posthorn, self-hosted mail gateway",
    summary: "Self-hosted email gateway between your apps and a transactional mail provider (Postmark, Resend, Mailgun, AWS SES, or outbound-SMTP). Three ingress shapes (HTTP form, HTTP API, SMTP). One Docker co...",
    content: "",
    category: "dev",
    image_url: "/card-news/show-hn-posthorn-self-hosted-mail-gateway.png",
    external_link: "https://github.com/craigmccaskill/posthorn",
    tags: ["Show", "HN", "Posthorn"],
    created_at: "2026-05-27",
    span: "",
  },
  {
    id: 55,
    slug: "hyundai-boston-dynamics-atlas-learn-by-watching",
    title: "Hyundai·Boston Dynamics — Atlas, 인간 시연 영상으로 학습",
    summary: "현대차·보스턴 다이내믹스가 Atlas 휴머노이드를 인간 작업 영상 시청만으로 학습시키는 새 학습 파이프라인을 공개. 텔레오퍼레이션·시뮬레이션 의존도를 낮추고 데이터 확보 비용을 크게 절감한 접근.",
    content: "",
    category: "ai",
    image_url: "/card-news/hyundai-boston-dynamics-atlas-learn-by-watching.png",
    external_link: "https://www.reddit.com/r/artificial/comments/1tnk2qd/hyundaiboston_dynamics_is_going_to_train_atlas/",
    tags: ["BostonDynamics", "Atlas", "휴머노이드"],
    created_at: "2026-05-26",
    span: "",
  },
  {
    id: 54,
    slug: "figure-ai-24-7-package-sorting-livestream",
    title: "Figure AI — 휴머노이드 8일간 24/7 패키지 분류 라이브스트림 공개",
    summary: "Figure AI가 휴머노이드 로봇이 8일 동안 24시간 쉬지 않고 패키지를 분류하는 모습을 라이브스트림으로 공개. 데모 영상이 아닌 실제 산업 환경 지속 동작을 보인 첫 휴머노이드 사례로 주목.",
    content: "",
    category: "ai",
    image_url: "/card-news/figure-ai-24-7-package-sorting-livestream.png",
    external_link: "https://www.reddit.com/r/artificial/comments/1tmtq3p/figure_ai_had_a_livestream_of_their_robots/",
    tags: ["FigureAI", "휴머노이드", "물류로봇"],
    created_at: "2026-05-25",
    span: "",
  },
  {
    id: 53,
    slug: "musinsa-geometric-prior-25x-vlm-free",
    title: "무신사 — VLM 안 쓰고 Geometric Prior로 25배 빠른 의류 디테일컷",
    summary: "무신사가 의류 디테일컷 자동화에 VLM 대신 Geometric Prior 기반 전통 컴퓨터 비전을 채택해 25배 속도를 얻은 사례를 공개. 'AI 만능' 대신 도메인 사전지식 활용이 더 효율적이었다는 실전 회고.",
    content: "",
    category: "dev",
    image_url: "/card-news/musinsa-geometric-prior-25x-vlm-free.png",
    external_link: "https://techblog.musinsa.com/vlm%EC%9D%84-%EC%93%B0%EC%A7%80-%EC%95%8A%EC%9D%80-%EC%9D%B4%EC%9C%A0-geometric-prior%EB%A1%9C-25%EB%B0%B0-%EB%B9%A0%EB%A5%B8-%EC%9D%98%EB%A5%98-%EB%94%94%ED%85%8C%EC%9D%BC%EC%BB%B7-%EC%9E%90%EB%8F%99%ED%99%94-ea9dc5ca2add",
    tags: ["무신사", "ComputerVision", "GeometricPrior"],
    created_at: "2026-05-24",
    span: "",
  },
  {
    id: 52,
    slug: "woowahan-rag-chatbot-system-context",
    title: "우아한공방 — 시스템 맥락 가진 RAG 챗봇 개발기",
    summary: "우아한형제들이 사내 시스템 맥락을 이해하는 RAG 챗봇 서비스를 공개. 단순 문서 검색이 아닌, 사내 서비스·코드·운영 컨텍스트를 임베딩 단계에서 결합해 실제 답변 정확도를 끌어올린 구조.",
    content: "",
    category: "dev",
    image_url: "/card-news/woowahan-rag-chatbot-system-context.png",
    external_link: "https://techblog.woowahan.com/26319/",
    tags: ["우아한형제들", "RAG", "챗봇"],
    created_at: "2026-05-23",
    span: "",
  },
  {
    id: 51,
    slug: "line-adk-context-token-40-percent",
    title: "LINE — ADK 컨텍스트 엔지니어링으로 토큰 소비 40% 절감",
    summary: "LINE Engineering이 Agent Development Kit(ADK)에서 컨텍스트 엔지니어링 3가지 기법으로 토큰 소비를 40% 줄인 사례를 공개. 시스템 프롬프트 구조화·툴 결과 정리·세션 상태 관리가 핵심.",
    content: "",
    category: "dev",
    image_url: "/card-news/line-adk-context-token-40-percent.png",
    external_link: "https://techblog.lycorp.co.jp/ko/cut-token-usage-40-percent-with-adk-context-engineering",
    tags: ["LINE", "ADK", "컨텍스트엔지니어링"],
    created_at: "2026-05-22",
    span: "",
  },
  {
    id: 50,
    slug: "kakao-messaging-stress-test-ai",
    title: "카카오 — 메시징 서버 스트레스 테스트 노하우와 AI가 덜어 준 부분",
    summary: "카카오가 메시징 서버의 스트레스 테스트 노하우를 공개했다. 시나리오 작성·로그 분석 같은 반복 작업을 AI에 위임하고 엔지니어는 부하 모델링·이상 패턴 해석에 집중하는 분업 구조가 핵심.",
    content: "",
    category: "dev",
    image_url: "/card-news/kakao-messaging-stress-test-ai.png",
    external_link: "https://tech.kakao.com/posts/822",
    tags: ["카카오", "스트레스테스트", "AI협업"],
    created_at: "2026-05-21",
    span: "",
  },
  {
    id: 49,
    slug: "line-ai-qa-augment",
    title: "LINE — 'AI 는 QA 를 대체하지 않았다, 확장했다'",
    summary: "LINE Engineering 이 사내 QA 직무가 생성형 AI 도입 이후 어떻게 진화했는지 공개했다. 결론은 '확장'. AI 가 반복 테스트 작성·재현 시나리오 빌드를 맡고, QA 는 도메인 위험 탐색에 집중하는 분업 모델.",
    content: "",
    category: "dev",
    image_url: "/card-news/line-ai-qa-augment.png",
    external_link: "https://techblog.lycorp.co.jp/ko/ai-augments-qa-rather-than-replacing-it",
    tags: ["LINE", "QA", "생성형AI"],
    created_at: "2026-05-20",
    span: "",
  },
  {
    id: 48,
    slug: "ai-hardware-startup-funding-q2",
    title: "AI 하드웨어 스타트업 Q2 자금 — Groq·Cerebras·Tenstorrent 3강 구도",
    summary: "AI 추론 가속 하드웨어 스타트업의 Q2 자금 흐름이 Groq·Cerebras·Tenstorrent 의 3강 구도로 정리됐다. NVIDIA 의 추론 시장 지배를 깨려는 흐름이지만 데이터센터 점유율은 여전히 미미.",
    content: "",
    category: "news",
    image_url: "/card-news/ai-hardware-startup-funding-q2.png",
    external_link: "https://www.semianalysis.com/p/inference-race",
    tags: ["AI하드웨어", "Groq", "Tenstorrent"],
    created_at: "2026-05-19",
    span: "",
  },
  {
    id: 47,
    slug: "anthropic-enterprise-agent-blueprint",
    title: "Anthropic Enterprise Agent Blueprint — 8주 도입 표준 패키지 공개",
    summary: "Anthropic 이 엔터프라이즈 에이전트 도입 표준 패키지를 공개. 8주 안에 PoC → 프로덕션 1개 워크플로 출시가 목표. Computer Use + Claude Code + MCP 조합 베스트프랙티스 가이드 포함.",
    content: "",
    category: "trend",
    image_url: "/card-news/anthropic-enterprise-agent-blueprint.png",
    external_link: "https://www.anthropic.com/solutions/enterprise",
    tags: ["Anthropic", "엔터프라이즈", "에이전트"],
    created_at: "2026-05-18",
    span: "",
  },
  {
    id: 46,
    slug: "musinsa-ai-pipeline-harness",
    title: "무신사 — '하네스로 제어하는 AI 파이프라인', Slow Query 자동 사냥 사례",
    summary: "무신사 물류플랫폼팀이 Slow Query 수집 → 정합성 검증 → PR 생성 → 리뷰 반영까지를 'AI 하네스'로 자동화한 경험을 공유했다. CloudWatch + LLM + 자체 휴리스틱 조합이 핵심. 매주 반복되던 작업이 사라졌다.",
    content: "",
    category: "dev",
    image_url: "/card-news/musinsa-ai-pipeline-harness.png",
    external_link: "https://techblog.musinsa.com/",
    tags: ["무신사", "AI파이프라인", "DevOps"],
    created_at: "2026-05-17",
    span: "",
  },
  {
    id: 45,
    slug: "stable-lm-3-edge-deploy",
    title: "StableLM 3 — 1.6B 모델로 GPT-3.5 급 한국어 성능, 모바일 추론 가능",
    summary: "Stability AI 의 StableLM 3 1.6B 모델이 한국어 KMMLU 에서 GPT-3.5 급 성능. INT4 양자화 시 720MB. 갤럭시 S24 / iPhone 16 에서 온디바이스 추론 데모 공개됨.",
    content: "",
    category: "ai",
    image_url: "/card-news/stable-lm-3-edge-deploy.png",
    external_link: "https://stability.ai/",
    tags: ["StableLM", "온디바이스", "한국어"],
    created_at: "2026-05-16",
    span: "",
  },
  {
    id: 44,
    slug: "openai-dev-day-spring-recap",
    title: "OpenAI Dev Day Spring — 핵심 발표 5개 요약, 'Realtime 가 진짜 게임체인저'",
    summary: "OpenAI Spring Dev Day 의 5대 발표 요약. Realtime API GA, Custom GPTs 수익화 GA, Computer Use 베타, Memory 표준 API, Voice agents. Realtime API 의 응답 지연 200ms 가 가장 호평.",
    content: "",
    category: "ai",
    image_url: "/card-news/openai-dev-day-spring-recap.png",
    external_link: "https://openai.com/blog/devday-spring-2026",
    tags: ["OpenAI", "DevDay", "Realtime"],
    created_at: "2026-05-15",
    span: "",
  },
  {
    id: 43,
    slug: "toss-frontend-architecture-2026",
    title: "토스 프론트엔드 — 2026 아키텍처 회고와 '왜 Remix 가 아니라 Next 였나'",
    summary: "토스 프론트엔드팀이 2026 아키텍처 회고를 공개했다. Remix 와 Next.js 사이에서 Next 를 택한 이유, SSR/CSR 비율 재조정, 그리고 모듈 페더레이션 폐기 결정까지. 결정의 근거가 명확해서 인기.",
    content: "",
    category: "dev",
    image_url: "/card-news/toss-frontend-architecture-2026.png",
    external_link: "https://toss.tech/article/frontend-architecture",
    tags: ["Toss", "Frontend", "Next.js"],
    created_at: "2026-05-14",
    span: "",
  },
  {
    id: 42,
    slug: "privacy-preserving-ai-techniques-survey",
    title: "프라이버시 보존 AI 기법 서베이 — DP·연합학습·TEE 의 실전 트레이드오프",
    summary: "MIT-IBM 공동 서베이가 프라이버시 보존 AI 의 세 축(Differential Privacy / Federated Learning / Trusted Execution Env)의 실전 성능을 비교. '하나만 쓰지 마라'가 결론. 의료·금융 도입 가이드 함께.",
    content: "",
    category: "trend",
    image_url: "/card-news/privacy-preserving-ai-techniques-survey.png",
    external_link: "https://arxiv.org/list/cs.CR/recent",
    tags: ["프라이버시", "연합학습", "DP"],
    created_at: "2026-05-13",
    span: "",
  },
  {
    id: 41,
    slug: "naver-hyperclova-x-2",
    title: "네이버 HyperCLOVA X 2.0 — 코드·수학 전용 변형 분리 출시",
    summary: "네이버가 HyperCLOVA X 2.0 를 발표했다. 범용 모델 외에 코드 전용(X-Coder)·수학 전용(X-Math) 변형을 분리. 한국어 코딩 벤치마크 자체 데이터셋도 함께 공개. NCloud 사용자 무료 일부 제공.",
    content: "",
    category: "ai",
    image_url: "/card-news/naver-hyperclova-x-2.png",
    external_link: "https://clova.ai/hyperclova",
    tags: ["네이버", "HyperCLOVA", "한국어AI"],
    created_at: "2026-05-12",
    span: "",
  },
  {
    id: 40,
    slug: "ai-music-billboard-rule",
    title: "Billboard, AI 생성 음악 차트 진입 규칙 명문화 — '인간 창작 비중 50% 이상'",
    summary: "Billboard 가 AI 음악 차트 등재 가이드라인을 공식화했다. '인간 작곡·작사·편곡 기여도 50% 이상 증빙'이 핵심. RIAA 와의 협의 결과. 가상 가수 시장에는 큰 영향 없을 전망.",
    content: "",
    category: "news",
    image_url: "/card-news/ai-music-billboard-rule.png",
    external_link: "https://www.billboard.com/",
    tags: ["AI음악", "Billboard", "저작권"],
    created_at: "2026-05-11",
    span: "",
  },
  {
    id: 39,
    slug: "gpu-secondary-market-crash",
    title: "H100 세컨더리 시장 30% 급락 — '훈련 GPU 잉여' 시그널?",
    summary: "H100 SXM 모듈의 세컨더리(중고) 가격이 1분기 대비 30% 급락. 클라우드 슬랏 가용성도 늘었다. 시장은 '훈련용 GPU 잉여' 신호인지, '단순 재고 조정'인지 의견 분분.",
    content: "",
    category: "trend",
    image_url: "/card-news/gpu-secondary-market-crash.png",
    external_link: "https://semianalysis.com/",
    tags: ["GPU", "H100", "시장"],
    created_at: "2026-05-10",
    span: "",
  },
  {
    id: 38,
    slug: "react-native-new-arch-default",
    title: "React Native 0.78 — New Architecture 가 기본값, Hermes 도 강제",
    summary: "React Native 0.78 부터 Fabric + TurboModules 가 default. Hermes 엔진도 강제. 1년 마이그레이션 준비 기간 끝. 미마이그레이션 앱은 'legacy mode' 로 격리되고 신규 기능 제한됨.",
    content: "",
    category: "dev",
    image_url: "/card-news/react-native-new-arch-default.png",
    external_link: "https://reactnative.dev/blog",
    tags: ["ReactNative", "Fabric", "Hermes"],
    created_at: "2026-05-09",
    span: "",
  },
  {
    id: 37,
    slug: "reasoning-model-tool-use-record",
    title: "Reasoning 모델 + Tool Use 동시 활성화 — Frontier 벤치마크 또 갱신",
    summary: "최신 Reasoning 모델들이 Tool Use 와 동시 활성화될 때 GPQA Diamond·MATH-500·OSWorld 까지 전부 SOTA 갱신. '도구 없는 추론'과 '추론 없는 도구'의 시대가 끝나간다.",
    content: "",
    category: "ai",
    image_url: "/card-news/reasoning-model-tool-use-record.png",
    external_link: "https://gpqa.io/",
    tags: ["Reasoning", "도구사용", "벤치마크"],
    created_at: "2026-05-08",
    span: "",
  },
  {
    id: 36,
    slug: "anthropic-computer-use-case-study",
    title: "Anthropic 발표 — Computer Use 가 RPA 라이센스 80% 줄인 보험사 사례",
    summary: "Anthropic 이 글로벌 보험사의 Computer Use 도입 사례를 공식 공개. 기존 UiPath/Blue Prism 라이센스 비용 80% 절감, 동시에 새 워크플로 도입 속도는 5배 빨라졌다. RPA 산업 재편의 기점.",
    content: "",
    category: "trend",
    image_url: "/card-news/anthropic-computer-use-case-study.png",
    external_link: "https://www.anthropic.com/customers",
    tags: ["Anthropic", "RPA", "도입사례"],
    created_at: "2026-05-07",
    span: "",
  },
  {
    id: 35,
    slug: "vercel-ai-sdk-v4-agentic",
    title: "Vercel AI SDK v4 — 에이전트 워크플로 정식 지원, 'streamText 만으론 끝'",
    summary: "Vercel 이 AI SDK v4 를 출시했다. 멀티스텝 에이전트 워크플로, 도구 호출 그래프, 사람 개입(human-in-the-loop) 패턴 모두 정식 API. AI 앱 개발의 새 베이스라인.",
    content: "",
    category: "dev",
    image_url: "/card-news/vercel-ai-sdk-v4-agentic.png",
    external_link: "https://sdk.vercel.ai/",
    tags: ["Vercel", "AISDK", "에이전트"],
    created_at: "2026-05-06",
    span: "",
  },
  {
    id: 34,
    slug: "kakao-honeybee-2",
    title: "카카오 Honeybee 2.0 — 한국어 멀티모달 모델, 자체 GPU 클러스터에서 학습",
    summary: "카카오가 Honeybee 2.0 멀티모달 모델 학습 완료를 알렸다. 자체 H100 1024장 클러스터에서 학습. KorOCR·KorVQA 벤치마크 SOTA. 카카오톡 챗봇·콜센터 통합이 1차 상용화 타깃.",
    content: "",
    category: "ai",
    image_url: "/card-news/kakao-honeybee-2.png",
    external_link: "https://tech.kakao.com/",
    tags: ["카카오", "Honeybee", "한국어AI"],
    created_at: "2026-05-05",
    span: "",
  },
  {
    id: 33,
    slug: "swe-bench-verified-1000",
    title: "SWE-bench Verified 1000 — 코딩 모델 사상 첫 95% 돌파, 인간 평균 추월",
    summary: "확장된 SWE-bench Verified 1000 에서 한 모델(미공개)이 95.2% 를 기록. 인간 시니어 엔지니어 평균(93%)을 처음으로 추월. 평가 환경 격리·재현성에 대한 검증은 진행 중.",
    content: "",
    category: "ai",
    image_url: "/card-news/swe-bench-verified-1000.png",
    external_link: "https://www.swebench.com/",
    tags: ["벤치마크", "SWE", "코딩AI"],
    created_at: "2026-05-04",
    span: "",
  },
  {
    id: 32,
    slug: "xai-grok-4-multimodal",
    title: "xAI Grok 4 — 멀티모달 추가, X 실시간 컨텍스트가 진짜 차별점",
    summary: "xAI 가 Grok 4 를 공개했다. 이미지·영상·실시간 X(트위터) 컨텍스트 통합. 벤치마크는 GPT-5·Claude Sonnet 4.5 와 동급. 차별점은 '지금 이 순간 트렌드' 에 대한 응답 정확도.",
    content: "",
    category: "ai",
    image_url: "/card-news/xai-grok-4-multimodal.png",
    external_link: "https://x.ai/",
    tags: ["xAI", "Grok", "Musk"],
    created_at: "2026-05-03",
    span: "",
  },
  {
    id: 31,
    slug: "karpathy-anthropic-pretraining",
    title: "Karpathy, Anthropic 사전학습팀 합류 — '재귀적 자가 개선' 라인업 완성?",
    summary: "Andrej Karpathy 가 Anthropic 사전학습팀 합류를 발표했다. Nick Joseph 휘하에서 'Claude 가 Claude 사전학습을 가속하는' 라인을 이끌 예정. OpenAI 이탈 3번째 시니어이자 강력한 시그널.",
    content: "",
    category: "ai",
    image_url: "/card-news/karpathy-anthropic-pretraining.png",
    external_link: "https://www.reddit.com/r/ClaudeAI/comments/1thw3bu/openai_cofounder_andrej_karpathy_just_joined/",
    tags: ["Karpathy", "Anthropic", "사전학습"],
    created_at: "2026-05-02",
    span: "",
  },
  {
    id: 30,
    slug: "toss-android-modularization",
    title: "토스 안드로이드 모듈화 — 200개 모듈 빌드 시간 1/3로 줄인 비법",
    summary: "토스 안드로이드팀이 200개 이상 모듈 구조에서 빌드 시간을 1/3 로 줄인 경험을 공유했다. KSP + Composite Build 조합, 그리고 의존성 그래프 정적 분석이 핵심. 코드 자체보다 그래프 모양을 먼저 본다.",
    content: "",
    category: "dev",
    image_url: "/card-news/toss-android-modularization.png",
    external_link: "https://toss.tech/",
    tags: ["Toss", "Android", "빌드"],
    created_at: "2026-05-01",
    span: "",
  },
  {
    id: 29,
    slug: "copilot-workspace-ga",
    title: "GitHub Copilot Workspace GA — '이슈 → PR' 풀 사이클 자동화",
    summary: "GitHub 가 Copilot Workspace 의 GA 를 알렸다. 이슈 → 명세 → 계획 → 구현 → 테스트 → PR 까지 풀 사이클 자동화. 엔터프라이즈 시트 비용은 월 39 달러, Pro 는 19 달러.",
    content: "",
    category: "dev",
    image_url: "/card-news/copilot-workspace-ga.png",
    external_link: "https://github.com/features/copilot",
    tags: ["GitHub", "Copilot", "에이전트"],
    created_at: "2026-04-30",
    span: "",
  },
  {
    id: 28,
    slug: "eu-ai-act-first-fine",
    title: "EU AI Act 첫 과징금 부과 — 채용 AI 운영사에 2700만 유로",
    summary: "EU 가 AI Act 시행 후 첫 과징금을 부과했다. 채용 자동화 AI 운영사가 '고위험 시스템 영향평가 미실시'로 2700만 유로(약 400억원). 미국·아시아 기업의 EU 운영 시 컴플라이언스 비용 재계산 중.",
    content: "",
    category: "news",
    image_url: "/card-news/eu-ai-act-first-fine.png",
    external_link: "https://digital-strategy.ec.europa.eu/en/policies/ai-act",
    tags: ["EU", "AIAct", "과징금"],
    created_at: "2026-04-29",
    span: "",
  },
  {
    id: 27,
    slug: "huggingface-spaces-100k-apps",
    title: "HuggingFace Spaces 10만 앱 돌파 — '비개발자 AI 빌더' 비중 35%",
    summary: "HuggingFace 가 Spaces 누적 10만 앱 돌파를 알렸다. 신규 앱 중 35% 가 'no-code/low-code' 카테고리. Gradio + Claude/GPT 결합 워크플로가 비개발자 진입 장벽을 크게 낮췄다.",
    content: "",
    category: "trend",
    image_url: "/card-news/huggingface-spaces-100k-apps.png",
    external_link: "https://huggingface.co/spaces",
    tags: ["HuggingFace", "Gradio", "노코드"],
    created_at: "2026-04-28",
    span: "",
  },
  {
    id: 26,
    slug: "python-313-free-threading-real",
    title: "Python 3.13 free-threading 실전 — NumPy·PyTorch 호환 매트릭스 공개",
    summary: "Python 3.13t (free-threading) 의 주요 과학 라이브러리 호환 매트릭스가 공식 정리됐다. NumPy 2.2·PyTorch 2.5 모두 'compatible'. GIL 없는 멀티스레딩이 데이터 사이언스 영역에서 본격 시동.",
    content: "",
    category: "dev",
    image_url: "/card-news/python-313-free-threading-real.png",
    external_link: "https://py-free-threading.github.io/",
    tags: ["Python", "GIL", "동시성"],
    created_at: "2026-04-27",
    span: "",
  },
  {
    id: 25,
    slug: "tesla-fsd-v14-supervised",
    title: "Tesla FSD v14 — 'Supervised' 라벨 유지, 그러나 개입 빈도 10배 감소",
    summary: "Tesla FSD v14 가 배포됐다. NHTSA 와의 합의로 'Supervised' 라벨은 유지되지만, 사용자 보고 평균 개입 빈도는 v13 대비 10배 줄었다. 머스크는 unsupervised 데모를 2026 하반기 예고.",
    content: "",
    category: "news",
    image_url: "/card-news/tesla-fsd-v14-supervised.png",
    external_link: "https://www.tesla.com/AI",
    tags: ["Tesla", "자율주행", "FSD"],
    created_at: "2026-04-26",
    span: "",
  },
  {
    id: 24,
    slug: "stable-diffusion-4-photoreal",
    title: "Stable Diffusion 4 — 포토리얼리즘 격차 거의 사라졌다",
    summary: "Stability AI 가 SD4 를 공개. ELO 점수에서 Midjourney v7 과 통계적 유의차가 사라졌다. 라이선스는 여전히 상업 사용 시 구독 필요. 오픈 가중치는 비상업 한정.",
    content: "",
    category: "ai",
    image_url: "/card-news/stable-diffusion-4-photoreal.png",
    external_link: "https://stability.ai/",
    tags: ["StableDiffusion", "이미지생성", "Stability"],
    created_at: "2026-04-25",
    span: "",
  },
  {
    id: 23,
    slug: "apple-intelligence-eu-rollout",
    title: "Apple Intelligence 유럽 출시 — DMA 협상 1년 만에 합의",
    summary: "Apple Intelligence 가 EU 에서 정식 출시. DMA(디지털시장법) 와의 충돌로 지연됐던 협상이 마무리됐다. 단, 일부 기능(Genmoji 일부)은 EU 한정으로 제외.",
    content: "",
    category: "news",
    image_url: "/card-news/apple-intelligence-eu-rollout.png",
    external_link: "https://www.apple.com/apple-intelligence/",
    tags: ["Apple", "EU", "DMA"],
    created_at: "2026-04-24",
    span: "",
  },
  {
    id: 22,
    slug: "korea-ai-startup-series-c-flood",
    title: "국내 AI 스타트업 시리즈 C 봇물 — Q1 누적 8000억원 돌파",
    summary: "국내 AI 스타트업의 시리즈 C+ 투자가 1분기에만 8000억원을 넘겼다. 업스테이지·뤼튼·트웰브랩스가 견인. 'AI 겨울 끝났다'는 평가와 'B2B SaaS 외엔 갈 곳 없다'는 회의론이 공존.",
    content: "",
    category: "news",
    image_url: "/card-news/korea-ai-startup-series-c-flood.png",
    external_link: "https://platum.kr/archives/series-c",
    tags: ["스타트업", "투자", "한국"],
    created_at: "2026-04-23",
    span: "",
  },
  {
    id: 21,
    slug: "computer-use-2-screen-grounding",
    title: "Anthropic Computer Use 2 — 스크린 grounding 정확도 90% 돌파",
    summary: "Anthropic 이 Computer Use 의 후속 버전을 공개했다. UI 요소 좌표 추론(grounding) 정확도가 OSWorld 벤치마크에서 90% 를 넘어섰다. RPA 업계가 '대대적 재편' 우려 중.",
    content: "",
    category: "ai",
    image_url: "/card-news/computer-use-2-screen-grounding.png",
    external_link: "https://www.anthropic.com/research/computer-use",
    tags: ["Anthropic", "ComputerUse", "RPA"],
    created_at: "2026-04-22",
    span: "",
  },
  {
    id: 20,
    slug: "mcp-protocol-w3c-track",
    title: "Model Context Protocol — W3C 표준화 트랙 진입, 멀티벤더 호환성 가시화",
    summary: "Anthropic 이 만든 MCP(Model Context Protocol)가 W3C Community Group 단계를 거쳐 표준화 트랙에 올랐다. OpenAI·Google 도 자사 구현체로 참여 의사 표명. 도구 호출 표준이 곧 통일된다.",
    content: "",
    category: "ai",
    image_url: "/card-news/mcp-protocol-w3c-track.png",
    external_link: "https://modelcontextprotocol.io/",
    tags: ["MCP", "표준", "W3C"],
    created_at: "2026-04-21",
    span: "",
  },
  {
    id: 19,
    slug: "react-19-server-actions-patterns",
    title: "React 19 Server Actions 패턴 모음 — Form 외 영역에서도 활용 가능",
    summary: "React 코어팀이 Server Actions 의 비 Form 활용 패턴(검색, 페이지네이션, 낙관적 업데이트)을 정리한 공식 가이드를 발표했다. RSC + Action 조합이 데이터 페칭의 새 표준으로 자리잡는 분위기.",
    content: "",
    category: "dev",
    image_url: "/card-news/react-19-server-actions-patterns.png",
    external_link: "https://react.dev/reference/rsc/server-actions",
    tags: ["React", "ServerActions", "RSC"],
    created_at: "2026-04-20",
    span: "",
  },
  {
    id: 18,
    slug: "ai-agents-enterprise-adoption-curve",
    title: "AI 에이전트 엔터프라이즈 도입 — 'PoC 80%, 프로덕션 12%' 의 골짜기",
    summary: "McKinsey 의 2026 1분기 조사. 글로벌 대기업 중 80%가 AI 에이전트 PoC 를 돌렸지만 프로덕션 배포는 12%에 불과. 가장 큰 장벽은 '책임 소재 불명확'과 '감사 추적 미흡'.",
    content: "",
    category: "trend",
    image_url: "/card-news/ai-agents-enterprise-adoption-curve.png",
    external_link: "https://www.mckinsey.com/featured-insights/artificial-intelligence",
    tags: ["에이전트", "엔터프라이즈", "도입"],
    created_at: "2026-04-19",
    span: "",
  },
  {
    id: 17,
    slug: "typescript-56-using-keyword",
    title: "TypeScript 5.6 — 'using' 키워드 stable, 리소스 자동 해제가 언어 기본이 된다",
    summary: "TypeScript 5.6 RC 에서 ECMAScript Explicit Resource Management 가 정식 지원으로 승격. 파일 핸들·DB 연결 같은 리소스를 try-finally 없이 자동 해제 가능. Node.js 24 와 함께 쓰면 효과 극대화.",
    content: "",
    category: "dev",
    image_url: "/card-news/typescript-56-using-keyword.png",
    external_link: "https://devblogs.microsoft.com/typescript/",
    tags: ["TypeScript", "ES2026", "리소스"],
    created_at: "2026-04-18",
    span: "",
  },
  {
    id: 16,
    slug: "woowahan-jpa-event-sourcing",
    title: "우아한형제들 — JPA 만으로 이벤트 소싱 구현한 결제 시스템 회고",
    summary: "배달의민족 결제팀이 별도 ES 프레임워크 없이 JPA + 이벤트 테이블 패턴만으로 이벤트 소싱을 구현한 경험을 공유했다. Axon·Eventuate 없이도 도메인 일관성을 지키는 실전 패턴이 핵심.",
    content: "",
    category: "dev",
    image_url: "/card-news/woowahan-jpa-event-sourcing.png",
    external_link: "https://techblog.woowahan.com/",
    tags: ["우아한형제들", "JPA", "이벤트소싱"],
    created_at: "2026-04-17",
    span: "",
  },
  {
    id: 15,
    slug: "meta-llama-4-405b-open",
    title: "Meta Llama 4 405B 공개 — 오픈 가중치 그대로, 로컬 추론 한계가 또 밀렸다",
    summary: "Meta 가 Llama 4 의 405B 변형을 오픈 가중치로 공개했다. 양자화 4bit 기준 단일 H100 80GB 두 대로 추론 가능. r/LocalLLaMA 에서는 '드디어 GPT-4o 대안이 손에 들어왔다' 는 반응.",
    content: "",
    category: "ai",
    image_url: "/card-news/meta-llama-4-405b-open.png",
    external_link: "https://ai.meta.com/llama/",
    tags: ["Llama", "Meta", "오픈소스"],
    created_at: "2026-04-16",
    span: "",
  },
  {
    id: 14,
    slug: "gemini-25-pro-multimodal-leap",
    title: "Gemini 2.5 Pro — 멀티모달 추론에서 GPT-5o 와 정면 비교 데이터 등장",
    summary: "Google DeepMind 가 Gemini 2.5 Pro 의 멀티모달 평가 결과를 공개했다. 영상·오디오·차트 이해 카테고리에서 GPT-5o 와 1-2점 차이의 박빙. 100만 토큰 컨텍스트 윈도우는 여전한 차별점.",
    content: "",
    category: "ai",
    image_url: "/card-news/gemini-25-pro-multimodal-leap.png",
    external_link: "https://deepmind.google/technologies/gemini/",
    tags: ["Gemini", "Google", "멀티모달"],
    created_at: "2026-04-15",
    span: "",
  },
  {
    id: 13,
    slug: "nvidia-blackwell-ultra-shipping",
    title: "NVIDIA Blackwell Ultra 공급 시작 — 하이퍼스케일러 우선 배정",
    summary: "NVIDIA 가 Blackwell Ultra(B300) GPU 의 본격 출하를 알렸다. 초기 물량의 70% 이상이 AWS·Azure·GCP·Oracle 등 하이퍼스케일러로 배정. 한국 기업은 2026년 하반기부터 접근 가능할 것으로 전망.",
    content: "",
    category: "news",
    image_url: "/card-news/nvidia-blackwell-ultra-shipping.png",
    external_link: "https://nvidianews.nvidia.com/",
    tags: ["NVIDIA", "GPU", "B300"],
    created_at: "2026-04-14",
    span: "",
  },
  {
    id: 12,
    slug: "korea-ai-basic-act-effect",
    title: "한국 AI 기본법 시행 1년 — '고영향 AI' 기업 절반 컴플라이언스 미흡",
    summary: "AI 기본법 시행 1주년 점검 결과, 고영향 AI 서비스 운영 기업의 절반 가까이가 영향평가·투명성 의무를 제대로 이행하지 못한 것으로 드러났다. 과기정통부는 후반기 시정 명령을 예고했다.",
    content: "",
    category: "news",
    image_url: "/card-news/korea-ai-basic-act-effect.png",
    external_link: "https://www.korea.kr/news/policyNewsView.do",
    tags: ["AI규제", "한국", "컴플라이언스"],
    created_at: "2026-04-13",
    span: "",
  },
  {
    id: 11,
    slug: "nextjs-16-ppr-ga",
    title: "Next.js 16 GA — Partial Prerendering 정식 출시, App Router 가 표준 된다",
    summary: "Vercel 이 Next.js 16 정식 버전을 출시했다. PPR(Partial Prerendering)이 default 로 켜지며 정적 셸 + 동적 콘텐츠 분리가 자동화됨. Pages Router 는 deprecation 카운트다운 시작.",
    content: "",
    category: "dev",
    image_url: "/card-news/nextjs-16-ppr-ga.png",
    external_link: "https://nextjs.org/blog/next-16",
    tags: ["Next.js", "Vercel", "PPR"],
    created_at: "2026-04-12",
    span: "",
  },
  {
    id: 10,
    slug: "claude-sonnet-45-extended-thinking",
    title: "Claude Sonnet 4.5 — Extended Thinking 자동 활성화, 코딩 정확도 또 상승",
    summary: "Anthropic 이 Sonnet 4.5 에서 Extended Thinking 을 자동 트리거하도록 업데이트했다. 복잡도 임계치 넘으면 자동으로 사고 체인 확장. SWE-bench Verified 에서 또 한 차례 점수 상승 보고됨.",
    content: "",
    category: "ai",
    image_url: "/card-news/claude-sonnet-45-extended-thinking.png",
    external_link: "https://www.anthropic.com/news",
    tags: ["Claude", "Anthropic", "코딩"],
    created_at: "2026-04-11",
    span: "",
  },
  {
    id: 9,
    slug: "gpt5-dev-day-roadmap",
    title: "OpenAI Dev Day 2026 — GPT-5 로드맵 공개, '에이전트 OS'가 핵심",
    summary: "OpenAI 가 봄철 Dev Day 에서 GPT-5 를 단순 모델이 아닌 '에이전트 OS' 로 포지셔닝했다. Computer Use API 통합, 메모리·도구 표준화, 그리고 멀티 에이전트 오케스트레이션이 키노트 주제. 개발자들은 ChatGPT 의존도가 낮아질 것을 기대 중.",
    content: "",
    category: "ai",
    image_url: "/card-news/gpt5-dev-day-roadmap.png",
    external_link: "https://openai.com/devday",
    tags: ["OpenAI", "GPT-5", "에이전트"],
    created_at: "2026-04-10",
    span: "",
  },
  {
    id: 1,
    slug: "anthropic-claude-cowork-ga",
    title: "Claude Cowork 정식 출시 — Anthropic 데스크탑 에이전트, macOS·Windows GA",
    summary: "1월 리서치 프리뷰로 공개됐던 Anthropic 의 데스크탑 에이전트 Claude Cowork 가 macOS·Windows 정식 출시. RBAC, Group Spend Limit, OpenTelemetry, Zoom MCP 커넥터 등 엔터프라이즈 6종 기능 동시 탑재. 파일 접근·멀티스텝 실행·도구 통합을 그대로 데스크톱 UI 로 옮긴 형태.",
    content: "",
    category: "ai",
    image_url: "/card-news/anthropic-claude-cowork-ga.png",
    external_link: "https://9to5mac.com/2026/04/09/anthropic-scales-up-with-enterprise-features-for-claude-cowork-and-managed-agents/",
    tags: ["Claude", "Anthropic", "Cowork"],
    created_at: "2026-04-09",
    span: "",
  },
  {
    id: 2,
    slug: "anthropic-managed-agents-beta",
    title: "Anthropic Managed Agents 공개 베타 — Claude 에이전트 클라우드 호스팅",
    summary: "Anthropic 이 Cowork GA 발표와 같은 날 Managed Agents 를 공개 베타로 출시. 클라우드에서 호스팅되는 에이전트 형태로, 별도 인프라 없이 멀티 에이전트 워크플로 구축 가능. Claude Code 도 같은 날 정책 컨트롤 + Bedrock 셋업 마법사 추가로 엔터프라이즈 준비도 강화.",
    content: "",
    category: "ai",
    image_url: "/card-news/anthropic-managed-agents-beta.png",
    external_link: "https://www.testingcatalog.com/anthropic-launches-claude-cowork-in-general-availability/",
    tags: ["Anthropic", "Managed Agents", "에이전트"],
    created_at: "2026-04-09",
    span: "",
  },
  {
    id: 3,
    slug: "anthropic-project-glasswing-mythos",
    title: "Anthropic Project Glasswing — Mythos Preview, 수천 개 제로데이 자율 발견",
    summary: "Anthropic 이 Opus 상위 티어 모델 Mythos Preview 와 방어 전용 이니셔티브 Project Glasswing 공개. 모든 주요 OS·웹 플랫폼에서 수천 개의 high/critical zero-day 를 자율 발견 (99%+ 미패치 상태). OpenBSD TCP 스택 27년 묵은 취약점, FFmpeg H.264 코덱 16년 묵은 결함까지 적발. 일반 공개 대신 AWS·Apple·Google·MS·NVIDIA·Linux Foundation 등 40+ 파트너에 한정 제공.",
    content: "",
    category: "ai",
    image_url: "/card-news/anthropic-project-glasswing-mythos.png",
    external_link: "https://www.anthropic.com/glasswing",
    tags: ["Anthropic", "Mythos", "보안"],
    created_at: "2026-04-08",
    span: "",
  },
  {
    id: 4,
    slug: "eu-ai-act-omnibus-negotiation",
    title: "EU AI Act Omnibus — 고위험 AI 의무 2027.12 로 연기 협상 본격화",
    summary: "유럽위원회가 작년 11월 발의한 Digital Omnibus on AI 가 트릴로그 단계 진입. 고위험 AI 시스템(Annex III) 적용일을 2026.8.2 → 2027.12.2 로 연기하는 게 핵심. 의료기기·산업기계·완구·커넥티드카처럼 기존 EU 규제와 중첩되는 영역의 면제 여부가 쟁점. 협상 실패 시 원안 8.2 발효 가능성도 살아있어 컴플라이언스 팀 비상.",
    content: "",
    category: "news",
    image_url: "/card-news/eu-ai-act-omnibus-negotiation.png",
    external_link: "https://iapp.org/news/a/ai-act-omnibus-what-just-happened-and-what-comes-next",
    tags: ["EU", "AI규제", "Omnibus"],
    created_at: "2026-04-08",
    span: "",
  },
  {
    id: 5,
    slug: "google-veo-31-free-public-access",
    title: "Google Veo 3.1, 모든 Google 계정 무료 개방 — 월 10회 영상 생성",
    summary: "Google 이 Veo 3.1 을 모든 개인 Google 계정에 무료 개방. 월 10회 720p/8초 영상 + 1080p·4K 업스케일링 기능 함께 제공, 구독·신용카드 불필요. 4.7 에는 Veo 3.1 Fast 가격 인하 + Lite 모델 출시로 개발자용 비용도 절반 이하로 떨어짐. Vids.new 에서 즉시 사용 가능.",
    content: "",
    category: "ai",
    image_url: "/card-news/google-veo-31-free-public-access.png",
    external_link: "https://www.ghacks.net/2026/04/07/google-opens-veo-3-1-ai-video-generation-to-all-users-with-free-monthly-access/",
    tags: ["Veo3", "Google", "영상생성"],
    created_at: "2026-04-07",
    span: "",
  },
  {
    id: 6,
    slug: "nvidia-blackwell-ultra-platform",
    title: "NVIDIA Blackwell Ultra 발표 — GB300 NVL72, AI 추론 1.5배 향상",
    summary: "NVIDIA 가 GTC 2026 키노트 후속으로 Blackwell Ultra AI 팩토리 플랫폼을 공식 공개. GB300 NVL72 가 GB200 대비 AI 성능 1.5배, AI 팩토리 매출 기회 50배 (Hopper 대비). AWS·GCP·Azure·OCI 가 첫 인스턴스 제공 예정. Dynamo 오픈소스 추론 프레임워크 동시 공개로 reasoning AI 모델 배포 효율화.",
    content: "",
    category: "news",
    image_url: "/card-news/nvidia-blackwell-ultra-platform.png",
    external_link: "https://nvidianews.nvidia.com/news/nvidia-blackwell-ultra-ai-factory-platform-paves-way-for-age-of-ai-reasoning",
    tags: ["NVIDIA", "GPU", "Blackwell"],
    created_at: "2026-04-07",
    span: "",
  },
  {
    id: 7,
    slug: "frontier-model-forum-china-distillation",
    title: "OpenAI·Anthropic·Google, 중국 모델 카피 차단 — Frontier Model Forum 공동 대응",
    summary: "OpenAI·Anthropic·Google 이 Frontier Model Forum 채널을 통해 중국 경쟁사의 모델 distillation (adversarial 추출) 시도 정보를 실시간 공유하기로. 미국 프론티어 모델의 능력을 그대로 베끼는 사례가 늘면서, 평소 경쟁 관계인 회사들도 안보 명목으로 협업. AI 패권 경쟁의 새로운 국면이자 frontier 모델 IP 보호의 첫 공동 프레임워크.",
    content: "",
    category: "trend",
    image_url: "/card-news/frontier-model-forum-china-distillation.png",
    external_link: "https://www.bloomberg.com/news/articles/2026-04-06/openai-anthropic-google-unite-to-combat-model-copying-in-china",
    tags: ["Frontier Model Forum", "보안", "AI규제"],
    created_at: "2026-04-06",
    span: "",
  },
  {
    id: 8,
    slug: "broadcom-anthropic-tpu-3-5gw-deal",
    title: "Broadcom-Anthropic 3.5GW 칩 딜 — Google TPU 기반 컴퓨팅 확보",
    summary: "Broadcom 이 Anthropic 과 약 3.5GW 규모의 컴퓨팅 용량 공급 계약 확장 발표. Google 의 AI 프로세서(TPU) 기반 인프라를 Broadcom 이 중계하는 구조로, NVIDIA GPU 의존 일변도였던 AI 인프라 시장에 큰 균열을 내는 거래. 칩 공급망 다변화 추세 가속화 — AI 인프라 패권의 새 시즌 개막.",
    content: "",
    category: "news",
    image_url: "/card-news/broadcom-anthropic-tpu-3-5gw-deal.png",
    external_link: "https://www.cnbc.com/2026/04/06/broadcom-agrees-to-expanded-chip-deals-with-google-anthropic.html",
    tags: ["Broadcom", "Anthropic", "AI인프라"],
    created_at: "2026-04-06",
    span: "",
  },
  /* TECH-NEWS-PIPELINE-DATA:END */
];

export default function CardNewsPage() {
  return (
    <main className="pt-28 pb-24 px-6 md:px-10 max-w-6xl mx-auto">
      <PageHeading
        eyebrow="Card News · Reddit AI · Tech"
        count={CARD_NEWS_DATA.length}
        size="xl"
        title={
          <>
            What&apos;s<br />
            <span className="display-accent display-accent-coral">hot</span> today.
          </>
        }
        lead={
          <>
            Reddit <span className="text-em">r/artificial</span>,
            <span className="text-em"> r/technology</span>에서 엄선한 AI &amp; 기술 트렌드.
            클릭해서 요약과 원문 링크를 확인하세요.
          </>
        }
      />

      <CardNewsGallery items={CARD_NEWS_DATA} />
    </main>
  );
}
